### ISSUE TITLE
krssh design incompatible with ProxyCommand/ProxyJump

### ISSUE THREAD

**Issue by joushou** [kryptco/kr#104]
krssh is a utility designed to extract hostname information from the ssh client, and to extract the SSH handshake from the network connection. It works by intercepting the network connection of the ssh client through ProxyCommand, relaying the traffic through stdout/stdin. This is a MiTM performed to sniff the handshake in order to provide the app with a validated hostkey and hostname.

This implementation is "bad" for multiple reasons:

1. Performance. It bypasses all of SSH's network handling, and replaces it with a, in comparison, "dumb" proxy that relays traffic over stdout/stderr. Not only that, the proxy attempts to parse every single packet received past the first, despite only needing one. This will cause a significant overhead on top of all SSH connections. This design is by no means absurd, but it is suboptimal.

2. Compatibility. It cannot coexist with ProxyJump or ProxyCommand options for other hosts. For a "default install", the result is that krssh simply does not "engage" for hosts that already have a ProxyJump/ProxyCommand configured. From a users point of view, this means no in-app host verification, and having to wait for the hostAuther timeout to expire.

3. Security. krssh is guaranteed to fail in some setups, so the app must permit signing request that do not carry verifiable hostauth information. This means that the user can potentially be tricked to signing a malicious request by stripping host auth information, and a malicious request will be *automatically* signed if it came from a machine that currently has an automatic signing period in effect. 

My primary problem resides with 2., as ProxyJump/Command is used for a lot of my common hosts. The user experience is quite poor in this scenario, with the information provided on the client being mostly useless, as well as the noticeable slowdown from the hostAuth timeout.

The correct way to replace krssh would be to propose a new interface to the OpenSSH team that allows for SSH agents to obtain this information prior to signing, removing the hack that is krssh entirely. Having the SSH client itself relay the information is the only way to guarantee the availability of the information. This may seem like a large effort, but it might end up simpler than it seems if the OpenSSH team would accept such an implementation.

Support for requests without hostauth info - in case the user needs to work from a machine that does not provide up to date clients with the new interface -  could then be configurable: if enabled, they should be exempt from auto signing, and make it *very* clear that they are unknown requests. If disabled, as by default, the request should never even be presented to the user. Alternatively, krssh could be used as a hack only for older clients.

Up for discussion. Just airing my observations and thoughts.

**Comment by kcking** [comment]
Hi Kenny, thank you for diving into krssh and writing up a great view of its current shortcomings! I agree with all 3 of your points.

We would love to work with the OpenSSH team to see if host verification could be delegated to the ssh agent (especially with agent forwarding). In the short term, we are working on solutions we have direct control over for these 3 points.

Let's start with 2: 
Regarding ProxyCommand/Jump compatibility, I am working on a change to krssh that would allow the phone to receive hostauth info for both the proxy and destination host (this will require a config change by the user). I'm not seeing the same behavior you are on fresh install though, krssh is still invoked and a normal authentication request is pushed for the proxy, but I do get an "unknown host" request for the destination host. What config options are causing krssh to not be invoked for you?

**Comment by joushou** [comment]
Working with the OpenSSH team is of course a bit longer term, but if we can establish what we need, it might not be *that* long term.

When I say that krssh doesn't get invoked, I only mean krssh - the PKCS11Provider is still called, so while Kryptonite is silent (and slow, primarily due to hostAuth timeout), it *does* successfully login. Any ProxyCommand or ProxyJump directive on a host will override the * ProxyCommand directive, causing krssh to not instantiate. The pkcs11 provider is still called, of course, as the PKCS11Provider directive is not overwritten.

Consider the following configuration, which is relatively close to one that I often use:
```
Host jumper
    ProxyCommand fun-non-trivial-command %h %p

Host xyz
    ProxyJump jumper

Host *
   PKCS11Provider /usr/lib/kr-pkcs11.so
   ProxyCommand /usr/bin/krssh %h %p
   IdentityFile ~/.ssh/id_kryptonite
```

The non-trivial proxy-command directive is not a simple `ssh -W` command. In this case, `ssh xyz` will not instantiate krssh even once. If applicable, both logins will go through kryptonite as "unknown host", but the shell just looks frozen from a users point of view, partly due to krd's 1 second host auth timeout.

In a more "common" proxy scenario, krssh will instantiate for the first host, but none of the later jumps.

As for your change: I'm curious - how would you be able to receive hostauth info for the destination host?

**Comment by kcking** [comment]
The idea is that `krssh` can take a new argument that acts as `ssh -W`, but scans incoming traffic for hostauths. So if your ProxyCommand before was `ssh -W %h:%p proxy`, you can change it to `krssh -p "ssh -W %h:%p proxy"` and the IO to the parent SSH process will be the same, but `krssh` can print to stderr and hostauths will be sent to `krd`.

I have a prototype of this working locally with the following config template:
```
Host hop2
    ProxyCommand krssh -p "ssh -W %h:%p hop1"
Host dest
    ProxyCommand krssh -p "ssh -W %h:%p hop2"

#   Kryptonite config below
```
Where three Kryptonite requests happen sequentially, all with the correct hostnames on the phone. 

I need to clean up the implementation before pushing I think this will work.

I'm curious about the structure of your `fun-non-trivial-command`. Is it a `netcat` invocation?

**Comment by joushou** [comment]
Ah, yes! That would work. A little inconvenient, but  better than nothing. 

Yes, `ProxyJump host` is equivalent to `ProxyCommand ssh -W %h:%p host`, which is what most people use ProxyCommand for. Not sure if it's "just" a macro, or if the jump is handled internally in the SSH client.

As for my non-trivial-command: It's a small Go binary that establishes a TLS tunnel and behaves like netcat. Useful when presented with DPI firewalls. For extra effect, I usually combine it with a protocol detector so that a HTTPS request still works as intended.

It's a little bit obscure. A normal jump setup would have the first host be accessible without a proxy command.

**Comment by kcking** [comment]
Ah that command sounds useful!

I just pushed the ProxyCommand feature to the feature-krssh-proxycommand branch, would you like to give it a try?

**Comment by kcking** [comment]
Closing this as I merged the `-p` krssh option. Let me know if you run into any other issues.
