### ISSUE TITLE
Postinstall fails on NFS-mounted home directories

### ISSUE THREAD

**Issue by asgeirn** [kryptco/kr#108]
Home directories are NFS mounted with root squash. Postinstall fails to access files in home directory as it's running as root.

    touch: Failed to run touch on "/home/ambolt/.ssh/config": Permission denied
    Can not open /home/ambolt/.ssh/config: Permission denied.
    grep: /home/ambolt/.ssh/config: Permission denied
    /var/lib/dpkg/info/kr.postinst: 5: /var/lib/dpkg/info/kr.postinst: can not create /home/ambolt/.ssh/config:
    Permission denied

**Comment by kcking** [comment]
This should be resolved since we now modify ssh config on `kr pair` as $USER instead of on install.
