### ISSUE TITLE
kr pair does not modify ~/.ssh/config

### ISSUE THREAD

**Issue by Navisence** [kryptco/kr#109]
When pairing as a regular user the pairing seems to succeed however ssh to me.krypt.co is requesting for the regular ssh key password. No changes were made to the ~/.ssh/config file. Tried this for my existing config file and for a missing config file.

Found the necessary contents of the config file in /root/ssh/config - seems those were added during the installation of Kryptonite.

Update: observed this issue on Linux Mint Debian edition (LMDE2 Betsy) while on Linux Mint 17.3 Rosa the ~/.ssh/config file was updated as expected.

**Comment by kcking** [comment]
That's correct, the ssh config is only modified on install. We try to drop sudo so that your normal user's ssh config is modified. Were you logged in as root when installing on Betsy, or just sudo-ed?

If this becomes a common problem, we may move ssh config changes to kr pair instead of install

**Comment by Navisence** [comment]
Both on Betsy and Rosa I used sudo to do the install. It appears that on Betsy dropping out of sudo didn't happen while on Rosa it did.

**Comment by jakdept** [comment]
In general, for advanced users it would probably be good to document the ssh config needed for this to work. I believe you just need:

```
	PKCS11Provider /usr/local/lib/kr-pkcs11.so
	ProxyCommand /usr/local/bin/krssh %h %p
	IdentityFile ~/.ssh/id_kryptonite
```

However, I'm guessing. And, I don't like the idea of sending everyone my SSH key - but I'm fine with writing my own config, I just had to determine what was needed.

**Comment by kcking** [comment]
Thank you @Navisence I will look into this

@jakdept Yes that is correct, we add the default keys to make sure we do not break anyone's existing setup. We will add an explanation for each ssh_config option in our install page at krypt.co/install

**Comment by kcking** [comment]
We now modify ssh config on `kr pair` instead of on install, which should resolve this issue.
