### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by orclev** [kryptco/kr#110]
Unless I missed it somewhere you currently don't maintain a change log file. This means that the only way to determine what's different from release to release is to look at all the commits in between an arbitrary pair of release tags. It would be nice if instead we could simply read a bulleted release notes list in a change log file. 

Since you seem to be maintaining a fairly neat commit history you may want to look into something like clog to auto-generate your change log from your commit history.

**Comment by kcking** [comment]
Thank you for the clog pointer! I will check that out.

We have started maintaining a changelog at [https://krypt.co/app/krd_changelog/](https://krypt.co/app/krd_changelog/), and the kr upgrade notice now includes a link to this page as of kr 2.1.0.

**Comment by kcking** [comment]
Also check out github release tags, which will include changelogs from now on!
