### ISSUE TITLE
macOS handoff sometimes broken

### ISSUE THREAD

**Issue by agrinman** [kryptco/kr#112]

**Comment by jaydisc** [comment]
I reported and have this problem. If Kryptonite has been recently awakened, any successive attempts to Handoff a URL from iPhone Safari to Mac Safari fail. When the Safari icon appears in the Mac Dock, I click it, a new tab opens in Safari, it says "Opening Webpage from Handoff" in the address bar, and after ten seconds or so, times out with no feedback leaving me with an empty tab.

If I double-click the iPhone home button and swipe up the Kryptonite app to kill it, and re-perform the test, Mac Safari correctly completes the Handoff and displays the URL and loads the page.

I am able to repeat these test consistently.

I'm running an iPhone 7 with 10.3.2, and a 2016 MacBook running 10.12.5. Bluetooth-wise, I have a Magic Keyboard 2 and Magic Mouse 2 and an Apple Watch all around the area during these tests.

**Comment by kcking** [comment]
The bluetooth re-architecture has resolved this issue :)
