### ISSUE TITLE
Pinned Host Keys (known hosts) fails with same host/different ports

### ISSUE THREAD

**Issue by cghdev** [kryptco/kr#114]
It seems the **Known Hosts** option only keeps track of the hostname, but not the port (at least on the android app). So if you connect to a host that has multiple ssh servers on different ports (NAT with multiple hosts behind) it only allows connection to one of them:

```
Kryptonite > Requesting SSH authentication from phone
Kryptonite > Phone approval required. Respond using the Kryptonite app
Kryptonite > Public key for <hostname> does not match pinned key. If the host key has actually changed, remove the pinned key in Kryptonite.
```

This should keep track of the pair host:port and not just host.

Thanks.

**Comment by agrinman** [comment]
Yes, thanks for the catch! We'll push a fix for this shortly. It should just be an update to `kr`, stay tuned.

**Comment by kcking** [comment]
Just pushed the fix for this, next release of `kr` will likely be on Monday.

**Comment by cghdev** [comment]
Awesome, just tested it and works as expected. Thanks!
