### ISSUE TITLE
Bash completion of scp remote paths takes 30 seconds complete

### ISSUE THREAD

**Issue by JefStat** [kryptco/kr#117]
I assume this is actually because KR doesn't support the scp remote path bash completion and is falling back to my local ssh key after a 30s timeout.

**Comment by kcking** [comment]
scp tab completion seems to work fine in zsh for me (albeit with ~1s of latency). Do any requests appear in the Kryptonite app when you start completion?

**Comment by JefStat** [comment]
@kcking I didn't realize the approved notification appears when you do autocompletion on android.
Then this seems to be related to the android app then. I've been having trouble with Android not notifying until I put the app into the foreground today. Works quickly with the android app in the foreground.

**Comment by kcking** [comment]
What type of android phone are you using, and do you have Google Play services enabled? 

Also make sure that notifications are enabled for Kryptonite in your phone settings.

**Comment by JefStat** [comment]
> What type of android phone are you using

Nexus 6 w/ android version 7.0

> do you have Google Play services enabled

yes

> Also make sure that notifications are enabled for Kryptonite in your phone settings. 

check

**Comment by kcking** [comment]
This may be due to slight clock skew between your phone and laptop. We are addressing this in the coming Kryptonite/`kr` updates, but you can perform a quick sanity check by running
```
sudo ntpdate ntp.ubuntu.com
```
and trying again.

Let us know if this helps!

**Comment by kcking** [comment]
closing for now -- feel free to reopen if you're still having issues!
