### ISSUE TITLE
Problem with pinned key?

### ISSUE THREAD

**Issue by rtfpessoa** [kryptco/kr#118]
Hi,

Not sure if anyone else already reported this, but I could not find it. I am getting this error and I have no idea what might be the problem.

The server to which I am trying to connect changed but the ip was assigned to a new one. I deleted my know_hosts in my computer. Do I need to delete them on the app? Where can I do it?

```
Kryptonite ▶ Requesting SSH authentication from phone
Kryptonite ▶ Public key for <IP HERE> does not match pinned key. If the host key has actually changed, remove the pinned key in Kryptonite.
sign_and_send_pubkey: signing failed: agent refused operation
Authentication failed.
```

How should I proceed?

**Comment by rtfpessoa** [comment]
Sorry I already found the know hosts in the settings. For some reason I misread it multiples times.

**Comment by kcking** [comment]
No problem! Let us know if you think there's a clearer message we could use.

**Comment by rtfpessoa** [comment]
I guess it was mostly my fault, but if possible, in the app, when I click in that error send me to the known hosts and also, even better, highlight the one that cause the problem would be amazing.

**Comment by kcking** [comment]
Agreed, I have created an issue here that you can follow if you like :) 
https://github.com/kryptco/kryptonite-ios/issues/62

**Comment by rtfpessoa** [comment]
Nice 👍

**Comment by danielwii** [comment]
`Kryptonite ▶ Public key for *.*.*.* does not match pinned key. If the host key has actually changed, remove the pinned key in Kryptonite.`
Where can I remove the key?

**Comment by OGKevin** [comment]
@danielwii inside the kr app on your phone

goto setting -> know hosts. there you should be able to remove the pinned key 👍

**Comment by danielwii** [comment]
Tks, didn't notice it, it's working now.

**Comment by radix** [comment]
I don't see "Settings -> known hosts" in the krypton app on my phone any more. Can someone please let me know how I can remove a pinned key?

**Comment by daenney** [comment]
I couldn't find this option in the Developer tab at first b/c at least on an iPhone 8 the screen isn't big enough, so it overlaps with some of the other stuff on it. The view also doesn't scroll, which seems to suggest it's some static background that just doesn't fit right?

![image from ios](https://user-images.githubusercontent.com/569574/45623834-e7148380-ba88-11e8-876a-fa7fb34fcc9b.jpg)

**Comment by agrinman** [comment]
@daenney sorry about this, bug on our end. Didn't accounted for the zoomed screen settings. We'll fix asap in an upcoming release. Thanks!

**Comment by daenney** [comment]
Awesome, thank you!

**Comment by ttheune** [comment]
Don't know if this should be a separate issue or not, but is there anyway to search through the knownkeys?  With AWS instances and such, I've literally hundreds to scroll through.  Very much needle in a haystack scenario here.

**Comment by pryorda** [comment]
It would be nice if this was set as a tab "hosts," then from there click and hold on each to pin or unpin

**Comment by viggy96** [comment]
I've noticed I get this problem between using Krypton on WSL and Linux. I can unpin the key in the app then use it on Linux for example. Then when I go to WSL, it complains about the pinned key. Then I can unpin the key can use it in WSL. But then I go back to Linux and it complains there.
