### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by achikin** [kryptco/kr#121]
Are there any instructions on how to remove krypt.co from my computer?

**Comment by kcking** [comment]
Yes, the `kr uninstall` subcommand removes the added ~/.ssh/ssh_config lines and `kr` binaries. We'd love to hear what wasn't working for you.

**Comment by achikin** [comment]
I forgot my phone in my car and couldn't pull from github.

**Comment by noamtamim** [comment]
Please add this to the FAQ. I uninstalled by using `brew uninstall` and then I had to manually fix git config and ssh config.

**Comment by bytelucas** [comment]
Just some feedback - for me I've had to uninstall after a month of using it because the frequent request timeouts and iOS bugs were becoming more of an issue than it was worth. Hopefully I'll come back to try kryptco again in the future though :slightly_smiling_face:

**Comment by StoppingBuck** [comment]
@lucasjohnston Exactly the same for me. I'm also uninstalling now after having experienced #245 more times than I'd like to remember.
Kryptco definitely has potential, but as an SSH agent I think it needs a little longer in the oven before I can use it in my daily work.

**Comment by ChenLi0830** [comment]
Ran `kr uninstall` and experienced issue with `/usr/local/bin/krssh: No such file or directory`

Had to manually comment `kr` related lines in `~/.ssh/config` file
```
Host *
        AddKeysToAgent yes
        UseKeychain yes
        # IdentityAgent ~/.kr/krd-agent.sock
        # ProxyCommand /usr/local/bin/krssh %h %p
        # IdentityFile ~/.ssh/id_krypton
        IdentityFile ~/.ssh/id_ed25519
        IdentityFile ~/.ssh/id_rsa
        IdentityFile ~/.ssh/id_ecdsa
        IdentityFile ~/.ssh/id_dsa
```

**Comment by timbl** [comment]
For em, I got a new phone, had Kypton on it, but couldn't see how to re-pair it with my laptop;

And then need to push to npm and kr wanted to sign the commit,  so kr uninstall./
But it didn't fix my  ssh config file or whatever causes it to for   npm/git/gpg signing ...

Propose:  that kr have commands to undo the damage to each place it has patched itself in, enable re-enable it for eg ssh.

**Comment by kesenwang** [comment]
> Ran `kr uninstall` and when trying to use ssh in github I experienced this error : `/usr/local/bin/krssh: No such file or directory`
> 
> Had to manually comment `kr` related lines in `~/.ssh/config` file
> 
> ```
> Host *
>         AddKeysToAgent yes
>         UseKeychain yes
>         # IdentityAgent ~/.kr/krd-agent.sock
>         # ProxyCommand /usr/local/bin/krssh %h %p
>         # IdentityFile ~/.ssh/id_krypton
>         IdentityFile ~/.ssh/id_ed25519
>         IdentityFile ~/.ssh/id_rsa
>         IdentityFile ~/.ssh/id_ecdsa
>         IdentityFile ~/.ssh/id_dsa
> ```

Thank you for this, was trying to SSH into other domains on Mac OS 12, kept failing despite the initial install not actually completed. Removed those lines from config.
