### ISSUE TITLE
krd hangs/becomes unavilable when multiple ssh connections start simultaneously

### ISSUE THREAD

**Issue by gae123** [kryptco/kr#128]
I have a tool that automatically  forks multiple ssh connections (some through rsync and scp). Very frequently when I do this, krd becomes unresponsive. Even after 'kr restart' it takes minutes to become responsive. At times I had to un-pair/re-pair to get things to work again.

This is an important use case for us and we will not be able to adopt this great tool until it is addressed.

**Comment by kcking** [comment]
We fixed a file descriptor leak that was causing this issue. Let us know if it happens again!
