### ISSUE TITLE
Private key file

### ISSUE THREAD

**Issue by OGKevin** [kryptco/kr#131]
I need to setup PHPStorm to deploy to my dev jail. Password auth is off and only works with keypair. So its asking me for my private key location, which of course is not stored on my local machine. When i look in the `~/.ssh/config` file i see that its pointing to `~/.ssh/id_kryptonite` but this file doesn't exist.

So what should I put in when asked for my private key location ? SSH via terminal works fine. But how can i set it up with programs such as PHPStorm ?

**Comment by kcking** [comment]
That config line tells SSH to present the kryptonite key first, PHPStorm needs the private key file which never leaves the Kryptonite app. The Kryptonite key has to be used through the krd ssh-agent.

[This issue](https://youtrack.jetbrains.com/issue/PY-6311) says that at least partial ssh-agent support was added in a recent PHPStorm version. The Kryptonite SSH agent is located at `~/.kr/krd-agent.sock` . Let us know if you have any trouble getting that working.

**Comment by OGKevin** [comment]
Hmm I had the wrong build, installed the EAP build and see this option. However SSH is still failing `auth cancel`.

This page doenst say anything about specifying an agent https://blog.jetbrains.com/phpstorm/2017/05/phpstorm-2017-2-eap-172-2273/

Should i specify the kr agent somewhere 🤔 ?

**Comment by kcking** [comment]
The agent is usually specified by the `SSH_AUTH_SOCK` environment variable. Are you able to start  jetbrains from the command-line and prepend `SSH_AUTH_SOCK=$HOME/.kr/krd-agent.sock`?

**Comment by kcking** [comment]
closing for now -- feel free to reopen after trying the env var fix!

**Comment by OGKevin** [comment]
I was very busy didn't get a chance to fix this, i just SSH'ed via command line. Will try this in the coming week.
