### ISSUE TITLE
KR is noisy when installed but not in use

### ISSUE THREAD

**Issue by benmoss** [kryptco/kr#135]
I'd like to use KR on shared workstations, but my problem is that when KR is installed but not paired it still prints out notifications every time another SSH key is used. IE:

```
$  git pull
Kryptonite ▶ Workstation not yet paired. Please run "kr pair" and scan the QRCode with the Kryptonite mobile app.
Already up-to-date.
```

It'd be nice if I could configure KR to be quiet when it's unpaired.

**Comment by kcking** [comment]
Thanks for reporting, we will add an env var to silence this message in the next release

**Comment by kcking** [comment]
Just released a fix for this. Add `export KR_SILENCE_WARNINGS=1` to your environment (i.e. in `~.bashrc`) to silence unpaired and upgrade warnings.

**Comment by benmoss** [comment]
Cool, thanks! A slight nitpick: I still get 

```
no such identity: /Users/pivotal/.ssh/id_kryptonite: No such file or directory
no such identity: /Users/pivotal/.ssh/id_ed25519: No such file or directory
```

I don't know if there's anything that can be done about that though.

**Comment by kcking** [comment]
You can remove all of the `IdentityFile` lines from the config, they are just there to make sure our key is offered first and even if a specific host has an `IdentityFile` set.
