### ISSUE TITLE
kr upgrade closes immediately

### ISSUE THREAD

**Issue by rkkautsar** [kryptco/kr#143]
```bash
~/go/src/github.com/kryptco/kr master
❯ echo y | kr upgrade
Upgrade Kryptonite on this workstation? [y/N] 

~/go/src/github.com/kryptco/kr master
❯ 

~/go/src/github.com/kryptco/kr master
❯ echo N | kr upgrade
Upgrade Kryptonite on this workstation? [y/N] 
Aborting.

~/go/src/github.com/kryptco/kr master
❯ 
```

It closes *immediately* without errors or warning

**Comment by kcking** [comment]
What version of `kr` are you running currently, and what method did you use to install?

If you are installing from source, you should just pull the code and run `make install` to run the latest version.

**Comment by rkkautsar** [comment]
I was trying to upgrade from 2.2.1 to 2.2.7, installed from source. (in Arch)

Yes, I resort to that when it fails, but I think there should at least be a message telling me this.

**Comment by kcking** [comment]
We don't yet officially support Arch, but we are in the process of transferring ownership of the `kr-git` AUR package. Once this happens, we will add it to `kr upgrade` and our installation instructions. 

You're right, this failure should definitely print an error. Thanks for reporting!

**Comment by kcking** [comment]
Solved with https://github.com/kryptco/kr/commit/10f70c19605b3b67f4143dea6d39fd44eb004cf2
