### ISSUE TITLE
Push notifications through firewall and proxy

### ISSUE THREAD

**Issue by securityicon** [kryptco/kr#146]
Hi,

I have been using Kryptco for a few months now and love the simplicity. Well done and thank you.

Issue I recenly discovered is that when the initial call is made out for the push notifications to my phone I need some firewall rules to be opened. From what I can see from the source is that this is hosted on some AWS site.

It would also be a very good idea if this could be done through a proxy and that proxy support can be added to kr.

Can you confirm the url or hostname/IP's to add to my firewall.

Cheers,
G

**Comment by securityicon** [comment]
Some update:
I managed to add the following:

Host: sqs.us-east-1.amazonaws.com
Port: 5938
Protocol: TCP

But no proxy working yet.

**Comment by kcking** [comment]
Is 5938 the source or destination port?
That host name is for AWS SQS, which we use for delivering the response back to the computer. We use AWS's SNS service for push notifications from the computer to the phone. 

I recommend adding these three hosts, all with destination port 443 and TCP to your firewall outbound allow list:
- `sns.us-east-1.amazonaws.com`
- `queue.amazonaws.com`
- `sns.us-east-1.amazonaws.com`

Out of curiosity, which firewall are you using?

**Comment by kcking** [comment]
Closing for now -- feel free to reopen if you're still having issues
