### ISSUE TITLE
vs code makes ssh access to github periodically.

### ISSUE THREAD

**Issue by comfuture** [kryptco/kr#148]
Hi,

I'm using visual studio code that has been set by default to access to github to refresh vcs automatically. So I receive SSH Login request notification every 3 minutes.
Of course I can turn it off in editors' setting or allow for 3 hrs to prevent anoying pushes. But is there any way to avoid requesting notification on ssh login that was made by editors like vs code, atom, etc..
Or is there an option to force use my default id_rsa instead of my kr key in some accounts?

I hope this enhancement can make many other users happy.

Best.

**Comment by kcking** [comment]
There isn't a setting in vscode that allows you to specify a local key, and doing so would require adding your local key to GitHub, circumventing the security benefit of Kryptonite.

It would make sense for vscode to specify how often it should pull, but without this feature I just leave it disabled and pull manually.
