### ISSUE TITLE
error retrieving OS version: exec: "lsb_release" on amazon linux image

### ISSUE THREAD

**Issue by gae123** [kryptco/kr#150]
I am on an amazon image and see this. lsb_release is a ubuntu executable I think, why is it expecting it to be there, it should not print this error message.

```
$ kr restart
2017/09/28 03:02:23 error retrieving OS version: exec: "lsb_release": executable file not found in $PATH
Restarted Kryptonite daemon.
```

**Comment by kcking** [comment]
According to this post, https://forums.aws.amazon.com/message.jspa?messageID=519816 , it looks like AWS stripped it out of their AMI. `sudo yum install redhat-lsb` should fix this for you, and we will add it as a depedency to our rpm package so this doesn't happen in the future.

Thanks for reporting!

**Comment by kcking** [comment]
Now fixed in our latest rpm release
