### ISSUE TITLE
Add export GPG_TTY=$(tty) to ~/.profile, not ~/.bash_profile

### ISSUE THREAD

**Issue by asmeurer** [kryptco/kr#153]
After installing Kryptonite on my Mac, all my terminal shells started opening without any of my customizations. I figured out that it's because Krytonite created a file called ~/.bash_profile with `export GPG_TTY=$(tty)`. [Apparently](http://stefaanlippens.net/bashrc_and_others/) bash, for login shells, reads whichever of ~/.bash_profile, ~/.bash_login, and ~/.profile exists, in that order, so all my stuff in ~/.profile stopped being sourced. 

The Krytonite installer should detect which of these files already exist and write the GPG stuff to the lowest one in the chain that currently exists (it also should probably create ~/.profile instead of ~/.bash_profile if none of them do).

**Comment by kcking** [comment]
Sorry about that! I wasn't aware that bash stopped after the first file that exists. We will fix this logic in the next release.
