### ISSUE TITLE
kr crashes on iOS 11.1 (15B93)

### ISSUE THREAD

**Issue by OGKevin** [kryptco/kr#162]
Hey there,

My dumb ass accidentally updated to the latest public beta (forgot I had the beta profile enabled 🤦‍♂️ ). Apparently kr will crash on this version. This means I can't ssh/commit which is a huge blockade! 

Is it possible to push a quick fix for this ? Let me know if logs are needed on how these could be retrieved! 

ATM looking for a way to downgrade, but if this is an ez fix then there is no need to downgrade 👍

**Comment by kcking** [comment]
Is `kr` on your computer crashing, or the Kryptonite app on your iPhone?

**Comment by OGKevin** [comment]
aah fair enough. 

Kryptonite on iPhone

**Comment by agrinman** [comment]
@OGKevin I just tested on iOS 11.1 and things seem to be ok. When does the app crash? Does ssh/git signatures work while the app is open in the foreground?

**Comment by OGKevin** [comment]
Hmm thats really unfortunate. I already downgraded back to iOS 11.0. 

The app wouldn't even open, it crashes when I try to open it. Kr on MacBook gets stuck with the following message  `Kryptonite ▶ Requesting SSH authentication from phone`

But because I already downgraded because I needed Kryptonite to work I can't help debug/reproduce 😔 I do apologise for that tho.

**Comment by agrinman** [comment]
@OGKevin just checking are you on the app store version? (or are you on the testflight build)

**Comment by OGKevin** [comment]
@agrinman I was on the test flight build.

**Comment by agrinman** [comment]
@OGKevin The test flight build expired, but not to fear your key won't be deleted and you can install Kryptonite from the app store now (same build). I think the reason it wouldn't open is some iOS 11.1 weirdness with expired test flight builds. 11.1 should work just fine with the app store build but I guess it's too late to test that with you :)

**Comment by OGKevin** [comment]
🤦‍♂️ yea, well I mean after the update it stoped working 😆 so the only thing I could think of was the updating messing with it I totally didn't take test flight into consideration 🙈. If only this happened in the weekend! It happened on a work day and I really needed to be able to ssh and commit so downgrading seemed to be the quickest fix but not the smartest 😒.
