### ISSUE TITLE
getting slow

### ISSUE THREAD

**Issue by jorangreef** [kryptco/kr#167]
I have been using kr for the past few months since launch.

Lately, the ssh latency added by kr is starting to become unacceptable, even when access has already been granted for 3 hours.

**Comment by jorangreef** [comment]
It's death by a thousand cuts, every single ssh, scp, rsync or git push/pull command.

**Comment by jorangreef** [comment]
Latency is typically 3 seconds to a server which is only 20ms away.

**Comment by kcking** [comment]
Thanks for letting us know. What phone and operating system are you using?

**Comment by jorangreef** [comment]
**Phone:** iPhone 5S
**OS:** macOS Sierra and High Sierra (an issue on both)

**Comment by kcking** [comment]
Thanks, also which iOS version are you currently running?

**Comment by jorangreef** [comment]
iOS 11.1.1

**Comment by kcking** [comment]
We just released an update today to the way kr and Kryptonite use bluetooth, but there is a small bug with how iOS handles changing the app from a bluetooth central role to a peripheral role.

Make sure you are up-to-date with both kr and Kryptonite v2.3.0, then force quit and relaunch the iOS app (which fixes an iOS bug that prevents bluetooth from working in the background). 

Let us know if this helps!

**Comment by jorangreef** [comment]
Thanks, I updated to v2.3.0 on my phone, but when I run `kr upgrade` I get:
```
Upgrade Kryptonite on this workstation? [y/N] 
y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8164  100  8164    0     0   6842      0  0:00:01  0:00:01 --:--:--  6843
kr: Installing Kryptonite...
kr: Downloading Kryptonite.
######################################################################## 100.0%
kr: OpenSSL command line found, verifying downloaded binary hash...
kr: Downloaded binary hash incorrect. Aborting.
```

**Comment by jorangreef** [comment]
Also, in case it helps, running `kr debugaws` a few times gives:

```
Create SQS Queue took 4433ms
Send SQS Message took 319ms
Receive SQS Message took 993ms
AWS connectivity check succeeded.

Create SQS Queue took 1756ms
Send SQS Message took 437ms
Receive SQS Message took 719ms
AWS connectivity check succeeded.

Create SQS Queue took 1679ms
Send SQS Message took 1159ms
Receive SQS Message took 1060ms
AWS connectivity check succeeded.
```

**Comment by kcking** [comment]
What is the output `curl https://krypt.co/kr | grep BOTTLE_HASH`? My guess is that github/cloudfront caches haven't yet flushed for your region.

**Comment by jorangreef** [comment]
```
10.11) OS_NAME=el_capitan;  BOTTLE_HASH=8eb19cae9e600a1fce25c5e8d0b08b7589f26b055c48d998e599558672a9b718;;
10.12) OS_NAME=sierra;      BOTTLE_HASH=0c26baab3c204cdac590f9bb6c2b49d6332b234c2b97991cd41f7524a32f48c5; USE_KRBTLE=1;;
10.13) OS_NAME=high_sierra; BOTTLE_HASH=8c3a76db5d1705be9fe17385580ec740fc2dd88314fa91e4366471c174ae347e; USE_KRBTLE=1;;
```

**Comment by kcking** [comment]
Ok looks like Cloudfront is up to date, but Github is still behind. If it's not resolved tomorrow we can bump the version and create new binaries which should do the trick.

Thanks for the help debugging!

**Comment by jorangreef** [comment]
Thanks, I upgraded kr to the latest version and it's now down to about 1-2 seconds on average for an existing 3 hour session.

Just by the way, is it possible to not have notifications sent for subsequent logins from the same device within a 3 hour session? I am getting taps on my Apple Watch and beeps on my phone each time.

**Comment by OGKevin** [comment]
@jorangreef There is an option in the app to disable this.

Go to devices and then to the device you want to disable and there will be an option to disable approved notifications.

**Comment by jorangreef** [comment]
Thanks for your help, I did that already but I am still getting notifications for an approved sessions.

**Comment by OGKevin** [comment]
Hmm indeed, im also getting notifications with this option enabled and already approved for 3 hours 🤔 

Think we need to open a separate issue for this 👍
