### ISSUE TITLE
Anyone can see your aws credentials

### ISSUE THREAD

**Issue by sanjujosh** [kryptco/kr#168]
All krypto apps (iOS, Android) exposing secret keys including firebase and aws 
Please mask it, or anyone can impersonate your credentials. 

### Is it intentional ?

**Comment by kcking** [comment]
Thanks for reaching out -- yes this is intentional, the credentials are restricted such that each user can only access the resources they create. I will add a comment indicating this.

**Comment by sanjujosh** [comment]
That's perfect, thanks for quick reply.
