### ISSUE TITLE
All requests time out from my linux machine

### ISSUE THREAD

**Issue by SEUH** [kryptco/kr#169]
I've used kryptonite for probably 2 months now but since 2 days it fails completely on my local machine.

Git commit/push/pull run into timeout errors. So i tried to reinstall and pair again but pairing is still timing out.
This is a connection error so i ran "kr debugaws" and this is the result:
```
~/kr $ kr debugaws
SignatureDoesNotMatch: Signature not yet current: 20171127T094510Z is still later than 20171127T090011Z (20171127T084511Z + 15 min.)
	status code: 403, request id: adf07313-b21d-5010-8898-218660ca7dc1
```

I definitely don't know what to do. I've tested if maybe my connection to AWS is the problem but i can fully connect to all AWS services.

**Comment by OGKevin** [comment]
Don’t think this is AWS related but more like KR’s authetication system. Seems that the server time divers from your local machine time with 45mins 🤔.

**Comment by SEUH** [comment]
@OGKevin you're totally right. System time was off +1 hour, totally missed that. Problem solved :+1:
