### ISSUE TITLE
kr transfer aborts with error EOF

### ISSUE THREAD

**Issue by tru** [kryptco/kr#170]
I am just now trying to transfer my key to my new iPhone X - but it keeps aborting after pairing with my old phone:

```
Scan this QR Code with the Kryptonite mobile app to connect it with this workstation. Maximize the window and/or lower your font size if the QR code does not fit.
Paired successfully with identity
ssh-rsa XXXXX Success, paired with OLD Kryptonite device ✔

Next, kr will request user@hostname access logs from Kryptonite to get a list of hosts that you will need to authorize for your new Kryptonite public-key.
Kryptonite ▶ Requesting logs from phone

Error: EOF
```

This is on macOS 10.13.1 with kr version 2.3.0

**Comment by kcking** [comment]
Have you updated Kryptonite on the old phone to version 2.3.0?

**Comment by tru** [comment]
Yes just double checked and it’s on 2.3.0

**Comment by kcking** [comment]
It's possible that the old version of `krd` is still running. Can you try running `kr restart` then attempt the transfer again?

**Comment by tru** [comment]
Yeah thanks - that totally solved the issue.
