### ISSUE TITLE
I get this error when I attempt to transfer keys

### ISSUE THREAD

**Issue by posix4e** [kryptco/kr#178]
https://github.com/kryptco/kr/blob/8c6e337b6b11d716a286b422aa5ae62abd3d176b/kr/transfer_authority.go#L69

**Comment by kcking** [comment]
What version of the Krypton app are you using on your phone?

**Comment by posix4e** [comment]
I am on ios. It seems to be the newest version

**Comment by posix4e** [comment]
I get it with dry run as well

**Comment by kcking** [comment]
Try `kr codesign` and `ssh me.krypt.co` to make sure that you both have a PGP public key and a host in your logs. Then try `kr transfer` again (dry-run is fine).

**Comment by posix4e** [comment]
Sorry I tried it again, the logs get cleared out when I repair my old device

**Comment by kcking** [comment]
We force a re-pair so that the user confirms which device they want to copy authority _from_ (they may have already started paired with the new device). Logs of old paired sessions are stored in Krypton and should be included by the `kr transfer` command. Is this still not working for you?

**Comment by posix4e** [comment]
nothing has changed no

**Comment by kcking** [comment]
Which linux operating system are you using?

**Comment by posix4e** [comment]
Ubuntu

**Comment by jasonehines** [comment]
I am having the same issue using Solus.

**Comment by kcking** [comment]
Thanks for letting us know, @jasonehines, we are actively working on this. What type of phone are you using?

**Comment by jasonehines** [comment]
iPhone X (11.2.5) iOS Krypton (2.3.1) Solus kr (2.3.1)

**Comment by kcking** [comment]
We found the bug -- an fix to Krypton iOS will be available in the next couple of days and we'll post here when it's published.

Thanks again for reporting!

**Comment by agrinman** [comment]
Krypton iOS 2.3.2 is out now and should fix this issue! Please re-open if there are any issues.
