### ISSUE TITLE
Support unknown flags

### ISSUE THREAD

**Issue by ys** [kryptco/kr#186]
The Atom editor is passing normal flags supported by the gpg-agent like `--no-tty`, `--batch` and `--yes`.

This makes krgpg failed with a flag unknown. 

Would be great to have normal gpg flags allowed

**Comment by kcking** [comment]
Thanks for reporting this issue, we'll add support for these flags

**Comment by kcking** [comment]
Fixed in https://github.com/kryptco/kr/commit/a3306dae6430da21de4f4406b61469abd8c63a81
