### ISSUE TITLE
feature requests for team usablity

### ISSUE THREAD

**Issue by loeken** [kryptco/kr#196]
Really like the app so far, cannot wait for windows support so we could start using this.

In your docu i found
```kr team members --ssh --email alice@acme.co | kr add staging.acme.co```

are there any plans like
```kr team members --ssh --email alice@acme.co | kr revoke staging.acme.co``` 

It would be convenient to be able to remove the users quickly too.

Also, are there are plans on sharing access? Ideally I would like for a team-member to be able to request access to a certain user@host, then the team-leaders will get a request and can execute something like

```kr team members --ssh --email alice@acme.co | kr add staging.acme.co```
to add the user. ( ideally for a certain time window, even a simple timed popup on the app to quickly remove the access again, or some list where shared resources are listed and can be removed  )

**Comment by kcking** [comment]
Hi @loeken, thanks for reaching out!

Yes we plan to add `revoke/remove` support to complement `kr add` as well as a way to list who currently has access. Requesting/granting temporary access is a bit further off as we want to make sure the way we implement integrates well with most existing infrastructures.

How are you currently using SSH on windows? We do currently support Bash on Ubuntu on Windows, and are keeping an eye on native OpenSSH support.

**Comment by loeken** [comment]
Excellent!

with the "requesting access" i thought to simply have a function to ask another team member to run the "kr add" for a certain hostname, the removal part would just be an extra :)

I am using qubes/arch right now. The Windows users will most likely use it with putty, visual studio, maybe some scp clients
