### ISSUE TITLE
Changelog not correct

### ISSUE THREAD

**Issue by lazyguru** [kryptco/kr#197]
Your public changelog at https://krypt.co/app/krd_changelog/ is missing releases.  It currently shows 2.4.0 as the latest release and 2.3.0 as the release prior. However, I just updated from 2.3.1 to 2.4.2.  Where are the release notes for 2.3.1, 2.4.1, and 2.4.2?

**Comment by kcking** [comment]
Thank you for pointing that out. The changelog now includes all of those releases. We generally keep our changelog in the signed tag of each release located at https://github.com/kryptco/kr/releases, but forgot to populate the website as well.
