### ISSUE TITLE
Can't install 2.4.x

### ISSUE THREAD

**Issue by hbarcelos** [kryptco/kr#199]
I'm trying to install the latest version of `kr` from source, but it's failing during the build step.

`2.3.x` versions works just fine.

## System info

```
$ uname -a
> Linux henrique-7650 4.16.2-1-MANJARO #1 SMP PREEMPT 
>      Thu Apr 12 17:46:07 UTC 2018 x86_64 GNU/Linux

$ go version
> go version go1.10.1 linux/amd64

$ rustc -V                    
> rustc 1.23.0 (766bd11c8 2018-01-01)

$ cargo -V
> cargo 0.24.0 (45043115c 2017-12-05)
```

## Steps

1. `go get -v github.com/kryptco/kr`
2. `cd $GOPATH/src/github.com/kryptco/kr`
3. `git checkout 2.4.3`
4. `make install`

The output:
```
rm -rf bin lib Frameworks
mkdir -p bin
mkdir -p lib
mkdir -p Frameworks
go clean -cache || true
cd sigchain && CARGO_RELEASE=--release make libsigchain-with-dashboard
make[1]: Entering directory '/home/henrique/go/src/github.com/kryptco/kr/sigchain'
cd libsodium && ./configure --prefix=/home/henrique/go/src/github.com/kryptco/kr/sigchain/cross/linux-x86_64 && make clean && make && make install
/bin/sh: ./configure: No such file or directory
make[1]: *** [Makefile:6: cross/linux-x86_64/lib/libsodium.a] Error 127
make[1]: Leaving directory '/home/henrique/go/src/github.com/kryptco/kr/sigchain'
make: *** [Makefile:71: all] Error 2
```

**Comment by kcking** [comment]
Did you update submodules using `git submodule update --init --recursive` after cloning?

**Comment by hbarcelos** [comment]
It worked! Thank's a lot (:

I'm not well-versed in Go lang, I supposed `go get` would do this automatically, but apparently it does not.

Shouldn't this probably be explicit in the docs?

**Comment by kcking** [comment]
No problem! It might with the `-u` flag.

We do mention this in the Build Dependencies/Instructions part of our README. Glad the builds working now :)
