### ISSUE TITLE
Phone does not automatically allow requests while running in background.

### ISSUE THREAD

**Issue by defund** [kryptco/kr#204]
I have Krypton set up such that it automatically allows requests sent from my computer. However, this only seems to work when I am directly within the Krypton phone app. If my phone is in sleep mode, the request does not go through on my computer—even though the app process is still running. Once I open the phone app, it notifies me that it has allowed the request from that timestamp. I would ideally like Krypton to allow requests while my phone is in sleep mode. Is this possible?

**Comment by kcking** [comment]
What type of phone are you using? This sounds like Android's doze mode battery optimization behavior which can be changed by going to battery settings -> clicking the '...' in the upper-right -> Battery Optimization -> Drop down -> All Apps and setting Krypton to 'Not Optimized'.

**Comment by defund** [comment]
I have a Pixel 1; the problem remains even after I toggle that.

**Comment by kcking** [comment]
Ok thanks for trying that. Can you follow up at support@krypt.co with the `SNSEndpointARN` in your `~/.kr/pairing.json` file?

**Comment by defund** [comment]
Ok, will do.
