### ISSUE TITLE
Do not use xterm colors for QR codes

### ISSUE THREAD

**Issue by mnzt** [kryptco/kr#206]
Upon running `kr pair` on a machine with following modified colours in Xresources:

```
! black
*.color0:       #2ec8ae
```

kr will use this color when spitting out a QR code, as shown below
![image](https://user-images.githubusercontent.com/10098811/39861254-8b9e0522-542f-11e8-818e-a00565797564.png)

However, this makes scanning the code very difficult for the app due to lack of contrast, if not near impossible. Whilst this is technically my fault for 're-mapping' black to a non-black colour, I feel like kr could take intensive here to circumvent this potential issue

**Comment by kcking** [comment]
Thanks for reporting! This will be fixed in the next release
