### ISSUE TITLE
Hosts defined in .ssh/config show up as 'unknown host' on device

### ISSUE THREAD

**Issue by zifnab06** [kryptco/kr#207]
I have the following in my .ssh/config:

```
Host github
  Hostname github.com
Host review
  Port 29418
  Hostname review.lineageos.org
```

My kr public key is added to each of these. When I run `ssh github` or `ssh review`, this shows up as `zifnab @ unknown host`, and `all for 3h` does not seem to be honored.

**Comment by kcking** [comment]
Does `ssh me.krypt.co` show the correct hostname on the phone? Could you please send the output of `ssh -vv github` either here or to support@krypt.co

Thanks!

**Comment by zifnab06** [comment]
Sorry I somehow missed this. 

Everything appears to be suddenly working, I have no idea what's changed (more than likely a weird issue on my end), going to go ahead and close this. Thanks though :P
