### ISSUE TITLE
"kr add" not working as expected

### ISSUE THREAD

**Issue by ProckStar** [kryptco/kr#214]
When following the instructions to use Krypton with an SSH server that is already running, I get an error. (I changed the IP address in the copied text below) https://krypt.co/docs/start/upload-your-ssh-publickey.html

```
error: Found argument 'sprock@192.59.30.105' which wasn't expected, or isn't valid in this context

USAGE:
    kr add [OPTIONS] --server <server> 
```
The instructions I followed showed this command, which is what I used.
 `kr add <user>@<server>`

However, the usage instructions printed in the error look different. Not sure what command to use. I have no idea what OPTIONS are available and I don't know enough to understand the syntax of the `--server <server>` - example usage would be great to understand how to write the proper command.

When I run the test `ssh me.krypt.co` it all works great, it requests authentication from the phone, after I allow the connection one time I get the "Success. Request Allowed"

I have noticed when SSH'ng into my server the SSH key pairs must be working cause I don't have to enter my password, but I don't get an authentication request on the phone and the first line shows this ... 

`no such identity: /Users/scott/.ssh/id_ed25519: No such file or directory`

Here's the file structure when I review the .ssh directory on my computer ...

config
(directory)controlmasters
id_krypton.pub
id_rsa
id_rsa.pub
known_hosts

It's obvious there should be more files. The files are listed in the config, but are not present which I'm sure has something to do with the trouble.

Is there a way to regenerate the files? Should I uninstall Krypton from my computer and servers and start over?

I had this all working perfectly back in January when I first installed it, but I have since changed servers where I was using it. Now I would like to use Krypton again but not sure how to fix this.

Thanks ... Scott

**Comment by kcking** [comment]
Hi Scott,

Apologies, for the trouble, your installation all looks fine. The `kr add` syntax has changed and currently does not support team-less users. We will fix this shortly, but an alternative equivalent command will work right now:

```
ssh-copy-id -i ~/.ssh/id_krypton <user@server>
```

Please let us know if that helps.

**Comment by ProckStar** [comment]
Thank you and my skill level is just above dangerous lol

When I run it on one of my servers (ubuntu 16.04 LTS) I get 
`/usr/bin/ssh-copy-id: ERROR: failed to open ID file '/home/sprock/.ssh/id_krypton': No such file or directory
	(to install the contents of '/home/sprock/.ssh/id_krypton.pub' anyway, look at the -f option)`

**Comment by kcking** [comment]
Sorry for not specifying -- the command just needs to be run from your local machine, not the server. It will remotely add the Krypton key to the server you specify in the command.

**Comment by kcking** [comment]
Also, it looks like I forgot a `-f` flag -- the final command is

```
ssh-copy-id -f -i ~/.ssh/id_krypton <user@server>
```

**Comment by ProckStar** [comment]
No worries, I actually tried it on the local computer (mac os 10.11.6) and I get this
`-bash: ssh-copy-id: command not found`

Am I missing a dependency on my Mac?

**Comment by ProckStar** [comment]
Looks like I am, I'll install ssh-copy-id and get back with the results

**Comment by ProckStar** [comment]
SUCCESS!!

Thank you so much! Now I need to duplicate this on a couple more servers ;-)

**Comment by kcking** [comment]
Great! Glad we could help
