### ISSUE TITLE
[Question] Sending message from App -> Desktop

### ISSUE THREAD

**Issue by Mathieu-Gosbee-ConnectedLab** [kryptco/kr#218]
Is there a generic method of Sending a message from App (iOS/Android) -> KR desktop client?
I need to send custom configuration information from the KR Mobile App, to the KR Desktop app

Also, is there method on the KR desktop that allows generic message receptions

**Comment by kcking** [comment]
There isn't a generic request, what type of configuration information are you interested in? Additional fields could be added to `MeRequest`/`MeResponse`

**Comment by Mathieu-Gosbee-ConnectedLab** [comment]
I'll look into MeRequest/Response. It's just signed Git pgp Author information which I want to come from the App, not the git config. We, at Connected Lab, share computers and constantly dealing with commits under the wrong users.

**Comment by kcking** [comment]
This information is already in the pgp public key that is sent back to the desktop, so we can add a `kr` command to print it out. Then you could add a git hook / alias to set the committer name/email from the kr command.

**Comment by Mathieu-Gosbee-ConnectedLab** [comment]
At the moment I have it hook into the final bit of pairing sequence, added Author Name to the MeResponse, etc.. and then exec'ing the local git config to set the information. A git hook will work, but I still have to modify the response to have the correct name. For client work, and shared workspaces, we can't just rely on local gitconfig info.
