### ISSUE TITLE
kr Breaks SSH after uninstalling with brew

### ISSUE THREAD

**Issue by BrianChristie** [kryptco/kr#224]
After using brew to install and uninstall, kr leaves SSH broken.

Uninstalling any package with brew should undo all changes that were made and leave the system in a clean state.

`brew install kryptco/tap/kr`
`ssh me.krypt.co` -> works
`brew uninstall kryptco/tap/kr`
`ssh me.krypt.co` -> error
`/bin/bash: line 0: exec: /usr/local/bin/krssh: cannot execute: No such file or directory`

**Comment by toldjuuso** [comment]
I didn't even get it to install on Mojave anymore. Installing through the "Easy install" on the repo README fixed everything.

**Comment by kcking** [comment]
Sorry for the trouble, removing the `# Added by Krypton` lines in your ssh config will fix this. The recommended way to uninstall kr is the `kr uninstall` command which removes these lines from your ssh config. We cannot run a script to do this from a brew formula as far as I'm aware, arbitrary code can only be run on install.

@toldjuuso the brew formula should be working on Mojave as well. What type of issue did you run into?

**Comment by toldjuuso** [comment]
@kcking It seemingly crashed trying to install something on rust wasm after running upgrade command through brew. It said that Mojave is unsupported and the installation will not succeed. Unfortunately, I do not have the logs of that anymore. Removing all versions through brew and then installing through the sh pipe worked fine.

I am running fish shell which sometimes causes problems. No idea what went wrong here though, but everything is working fine now. ✌️

**Comment by kcking** [comment]
Ok good to hear. Closing this issue for now as I'm not aware of a solution to OP's problem other than running `kr uninstall` instead of `brew uninstall`
