### ISSUE TITLE
installing kr on arch linux

### ISSUE THREAD

**Issue by eyadsibai** [kryptco/kr#225]
I tried to install kr from github or the aur package and I am getting the same error:

```error:     Updating git repository `https://github.com/kryptco/ring`
error: failed to load source for a dependency on `ring`

Caused by:
  Unable to update https://github.com/kryptco/ring#958b46b2

Caused by:
  revspec '958b46b226bad1e4aab0d49e4d2cdd0c68becc29' not found; class=Reference (4); code=NotFound (-3)```

**Comment by kcking** [comment]
This issue should have been fixed yesterday. Can you try with a fresh checkout after running `rm -rf ~/.cargo/registry` to make sure an invalid dependency isn't cached?

**Comment by eyadsibai** [comment]
working now! thanks!
