### ISSUE TITLE
Require a "pairing password" to `kr pair` a new device.

### ISSUE THREAD

**Issue by donjaime** [kryptco/kr#229]
`kr pair` effectively makes your cellphone be the single source of truth for access to all of your systems. Cellphones fall out of pockets, or can be easily stolen. 

For usability reasons, most people don't maintain strong passwords to unlock their phones. Your 4-6 digit phone pin should not be last line of defense in the event of a device being stolen.

Laptops with keyboards at least have long passwords, and are harder to lose/steal.

Requiring a master password (configured on the phone during app setup, and stored +reverified via the secure enclave) during device pairing would neatly address this threat vector. Pairing should be a rare event, so this should not reduce usability much at all. While greatly increasing the security of the system as a whole.

**Comment by Bodup** [comment]
As it is now, the app already prompts for Touch ID when pairing a new device. Shouldn't that suffice?

**Comment by OGKevin** [comment]
Don't think that should be  implemented in KR then tho, but then in the dedicated android/ios app 🤔. 

Pairing on ios indeed ask for touch id.

**Comment by donjaime** [comment]
@OGKevin I was imagining entering the password at the command line via KR. But prompting on the mobile device probably makes more sense. I'll close this and consider re-opening as an issue on the android app instead.

@Bodup I was admittedly thinking about in the context of Android. You are right that touchID mediating access to the keychain probably suffices for iOS. A homogenous experience across android and iOS for pairing would be nice from a security predictability perspective. But it's not super important.
