### ISSUE TITLE
Go 1.11 compile error

### ISSUE THREAD

**Issue by indykish** [kryptco/kr#230]
Have you guys tried compiling in `go 1.11 rc1`

The `kryptco/go-crytpo` fails to compile. 

```
gitlab.com/rioos/ninja_turtles/vendor/github.com/kryptco/kr/vendor/github.com/kryptco/go-crypto/blake2b.supportsAVX2: relocation target runtime.support_avx2 not defined

gitlab.com/rioos/ninja_turtles/vendor/github.com/kryptco/kr/vendor/github.com/kryptco/go-crypto/blake2b.supportsAVX: relocation target runtime.support_avx not defined

```

I see that `kryptco/go-crytpo` is a fork of `https://github.com/golang/crypto`  with few additions cryptographic support.

https://github.com/kryptco/go-crypto/commit/00c23bbb201ac34f4df2897925c18efc1181d5f6
https://github.com/kryptco/go-crypto/commit/ba87603ee638331d0d191f6bb79eea6fecced4fe
https://github.com/kryptco/go-crypto/commit/234e0fafa9b683c1ad9a74d4fbb11139985c31b1
https://github.com/kryptco/go-crypto/commit/51f3d5387c633e197ca38af8102bd8295f69449f

The `kryptco/go-crypto` is downlevel ( a year old).  

Does the upstream `golang/crypto` contain the additional crytographic support patched in `kryptco/go-crypto`  ?

Do we still need this library  ? 

Why can't the fixes in `kryptco/go-crypto` be sent as a pull request in upstream.

**Comment by kcking** [comment]
Thank you for reporting -- this is now fixed in master. We need the blake2b Sum192 function. Our go-crypto dependency is now up to date with Go 1.11. Please let us know if you run into any other issues!
