### ISSUE TITLE
Cant export public key. "ssh: short read"

### ISSUE THREAD

**Issue by OGKevin** [kryptco/kr#232]
I got a new Iphone. So my private keys have not been transferred during the backup and restore process.

So i have to set everything up again relating to kryptco. 

However now I'm stuck and cant get to work because I cant export my public key. 

```
~ ⍉ ➜ kr copy
ssh: short read
~ ⍉ ➜ kr me
ssh: short read
~ ⍉ ➜ kr --version
kr version 2.4.10
~ ⍉ ➜ go version
go version go1.10.3 darwin/amd64
~ ⍉ ➜
```

This started happening after repairing my MacBook. 

Please help, as Im now stuck and can't access anything :(.

**Comment by OGKevin** [comment]
Seems to be related with https://github.com/golang/go/issues/24859

**Comment by OGKevin** [comment]
Alright, so after looking through the settings i see i needed to disable and re-enable developer mode. Then it regenerated a private key and everything seems to work now. Seems like a little design flaw imo.

**Comment by hajee** [comment]
Yes and it solved my issue. Sorry for bothering you guys. Although this show that probably the documentation could use a little extra love :-D

**Comment by mraxilus** [comment]
I'm still getting this issue after enabling developer mode.

**Comment by kcking** [comment]
Hi @mraxilus, did enabling developer mode bring you through the developer onboarding?

**Comment by kcking** [comment]
Ok thank you for the additional information. What type of phone are you using?

**Comment by mraxilus** [comment]
Original Pixel.

**Comment by mraxilus** [comment]
Yeah, that did it, is there anyway to keep the same keys in the future so I don't have to reshare my public keys? Basically, can I just copy the key from my some location old device to my new one next time?

**Comment by OGKevin** [comment]
@mraxilus that defeats the whole purpose of storing the key on your phone and what KR is trying to achieve 🤔

**Comment by psyanite** [comment]
Here's how I fixed it
open app
go to settings
enable developer mode
run 'kr pair' again
scan qr code
success, i see SSH key

**Comment by mraxilus** [comment]
@OGKevin I keep a backup of my private keys on my Linux distributions so when I reinstall the OS the machine can retain its credentials. If both my devices and my backup methods are secure I don't see how this is a problem.

**Comment by OGKevin** [comment]
@mraxilus fair enough.
