### ISSUE TITLE
kr fails to start

### ISSUE THREAD

**Issue by carterworks** [kryptco/kr#233]
I'm not sure what triggered this, but my `kr` util has broken.

When I start a `git pull` or `ssh`, it just hangs. Normally, it would go to `kr` and request credentials, but instead, no output is given. It waits for a minute, then `git` says "Could not read from remote repository". `ssh` fails in a similar way.

Uninstalling then reinstalling, or unpairing then repairing, does not change anything. Same with `kr restart`.

I'm running Linux Mint 18.3, if that helps.

**Comment by kcking** [comment]
Thanks for reporting. Can you send the output of `ssh -vv me.krypt.co` to support@krypt.co?

Also have you changed any vpn or proxy settings recently?

**Comment by ThatCarterMcBride** [comment]
Thanks for the quick response. I sent the output.

I haven't made any changes to proxy or vpn.

**Comment by ThatCarterMcBride** [comment]
I think the culprit is that `~/.ssh/id_krypton`, `~/.ssh/id_krypton-cert`, and the others are missing. How are those generated?
