### ISSUE TITLE
No public key after pairing

### ISSUE THREAD

**Issue by jakeprem** [kryptco/kr#235]
I installed the kr client (Ubuntu 16.04), and paired it with my phone. When I do so, instead of displaying the public key, it prints 
```
Paired successfully with identity
ssh: short read
```
Doing `kr me` gets the same result.

I've also tried on Ubuntu 18.04 and Manjaro(Arch), both with the same result, leading me to think the problem is with how kr is interacting with the Krypton app on my phone.

**Comment by agrinman** [comment]
Hi @jakeprem -- please make sure to enable developer mode (in the settings menu, top left gear icon). Sorry about this inconvenience -- we'll address this in an update soon.

**Comment by jakeprem** [comment]
That fixed it, thanks! Hopefully Google will pick up this issue for anyone else who runs into this.
