### ISSUE TITLE
Tracking unexpected access attempts

### ISSUE THREAD

**Issue by cro** [kryptco/kr#263]
Greetings,

Since I upgraded to 2.4.13 (which doesn't appear to have a release on the GitHub repo?) I've noticed many attempted logins to my GitHub account.  I have an Apple Watch so they are pretty obvious to me.  I have been getting them even when I am not at my computer--this morning alone my watch showed over 20 before I even started work.  How can I track down where these are coming from?

**Comment by cro** [comment]
Sorry, I was not clear--I mean SSH logins to access code repositories, not 2FA logins to the GitHub website.

**Comment by agrinman** [comment]
check your code editors: visual studio, IntelliJ, pycharm, etc. I believe there was a recent release that added periodic git fetches to one or more of these editors.

**Comment by cro** [comment]
Ah! That was it.  PyCharm is the culprit.  Thank you.
