### ISSUE TITLE
intellij idea git is keeping fetching

### ISSUE THREAD

**Issue by droid-Q** [kryptco/kr#265]
Don't know why.
![IMG_4B11B55A247B-1](https://user-images.githubusercontent.com/708277/56109189-e5a92c00-5f81-11e9-9839-d6cb887e404d.jpeg)
![CleanShot 2019-04-15 at 13 06 32@2x](https://user-images.githubusercontent.com/708277/56109190-e641c280-5f81-11e9-8344-e2d31efc9f97.png)

**Comment by agrinman** [comment]
<img width="1235" alt="Screen Shot 2019-04-15 at 1 43 18 AM" src="https://user-images.githubusercontent.com/356333/56109747-e9a46200-5f1f-11e9-9caf-ec93b1f21c3c.png">

**Comment by agrinman** [comment]
The new update autoenabled this setting for git fetch every 10min. You can disable it and this will stop.

**Comment by droid-Q** [comment]
@agrinman ok,thanks.
