### ISSUE TITLE
How have you handled krypt.co while on a plane?

### ISSUE THREAD

**Issue by pryorda** [kryptco/kr#269]
How have you guys handled krypt.co while on a plane without paying twice?

**Comment by agrinman** [comment]
For `kr` (SSH/Git)  bluetooth should make it work without internet. However, for U2F currently the browser extension `kr_u2f` doesn't support bluethooth.

**Comment by pryorda** [comment]
How do you get the ssh / girl to work with Bluetooth?? Is there docs?

**Comment by pryorda** [comment]
It just works after you connect the device and click connect network :)
