### ISSUE TITLE
Please add kr to brew

### ISSUE THREAD

**Issue by nicolaevladescu** [kryptco/kr#277]
Hi.

Although i find the install method of `kr` very fast and simple it's also rudimental and disappointing security wise. Any `curl | sh` even though it does not require `sudo` is a bad practice, and much more coming from a product that emphasises and enhances security.

Please add the `kr` program to brew.sh at least (at most all common package managers on all platforms).

Thank you.

**Comment by agrinman** [comment]
We have a brew install method already: brew install kryptco/tap/kr

**Comment by agrinman** [comment]
By the way, security wise these are equivalent

**Comment by nicolaevladescu** [comment]
Yes sorry i missed that, wanted to close this myself.

Well, i already trust brew.sh and it's trusted by a lot of people in general so although technically equivalent, but a bit more trustworthy.

Thank you for your feedback.
