### ISSUE TITLE
kr upgrade on MacOS Catalina

### ISSUE THREAD

**Issue by sumanthratna** [kryptco/kr#280]
I'm currently on `kr version 2.4.13`, on MacOS Version 10.15 Beta. 

Output of `kr upgrade`:
```
Upgrade Krypton on this workstation? [y/N] y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8289  100  8289    0     0  54176      0 --:--:-- --:--:-- --:--:-- 53824
kr: Installing Krypton...
kr: Unsupported OS X version 10.15. Krypton requires 10.11+
```

Running `kr -v` returns `kr version 2.4.13` again. 

Interestingly, krypton has been successfully signing Git commits (and `kr codesign test` is working).

**Comment by lucasjohnston** [comment]
Still not Catalina support, it's supposed to be released tomorrow 🙈

**Comment by agrinman** [comment]
Fixed. Thanks @lucasjohnston !
