### ISSUE TITLE
DNS lookup to me.krypt.co failing

### ISSUE THREAD

**Issue by tmitchell** [kryptco/kr#282]
The post-setup instructions say to attempt to ssh to `me.krypt.co` but this is failing with a DNS lookup error:

> %ssh me.krypt.co
> could not connect to remote: dial tcp: lookup me.krypt.co: no such host
> ssh_exchange_identification: Connection closed by remote host

For posterity, it currently resolves as a CNAME to `me-krypt-co-800488383.us-east-1.elb.amazonaws.com`

**Comment by nikkikom** [comment]
> For posterity, it currently resolves as a CNAME to me-krypt-co-800488383.us-east-1.elb.amazonaws.com

Not anymore.

**Comment by agrinman** [comment]
Apologies this test server was moved.
`ssh me.krypt.co` should now be deployed and working again.
