### ISSUE TITLE
Installation document needs to be updated

### ISSUE THREAD

**Issue by shidokamo** [kryptco/kr#296]
Hi,

The `kr` CLI Installation command described in the official document was failed with this message.

```sh
$ curl https://krypt.co/kr  | sh
Redirecting to https://www.krypt.co/kr
```

When I added `-L` option to curl to allow redirecting or when I change the URL to `https://www.krypt.co/kr`, I was able to download the installation script. Could you fix the installation document?

**Comment by agrinman** [comment]
Thanks, this is fixed now!
