### ISSUE TITLE
gpg signing freezes

### ISSUE THREAD

**Issue by brandonkal** [kryptco/kr#299]
error: gpg failed to sign the data
fatal: failed to write commit object

I've noticed kr has really been slowing down my work. Some days it works fine. Other days it refuses to sign every other commit or more frequently not at all.

**Comment by ykorzikowski** [comment]
Same here. Are there any plans to cluster krypton or using load balancers? Maybe switching to P2P is possible?

**Comment by agrinman** [comment]
Krypton uses SQS and push notifications, we don’t run any servers. The only thing I would suggest is try opening the app and seeing if speed improves? Obviously not a solution but at least would help diagnose the root cause.

**Comment by ykorzikowski** [comment]
Thx I will give it a try.
