### ISSUE TITLE
Krypton not working after last update

### ISSUE THREAD

**Issue by rmntkc** [kryptco/kr#300]
Hello everyone,
I have huge problem with Krypton, I would be literally locked out of my servers if I didn't have backup.
After yesterday update of macOS 10.15.4 (19E266), krypton won't start.

username@MBP ~ % ssh username@example.com
no such identity: /Users/username/.ssh/id_ed25519: No such file or directory
no such identity: /Users/username/.ssh/id_rsa: No such file or directory
no such identity: /Users/username/.ssh/id_ecdsa: No such file or directory
no such identity: /Users/username/.ssh/id_dsa: No such file or directory
username@example.com: Permission denied (publickey).
username@MBP ~ % cat .ssh/config 
# Added by Krypton
Host *
	IdentityAgent ~/.kr/krd-agent.sock
	ProxyCommand /usr/local/bin/krssh %h %p
	IdentityFile ~/.ssh/id_krypton
	IdentityFile ~/.ssh/id_ed25519
	IdentityFile ~/.ssh/id_rsa
	IdentityFile ~/.ssh/id_ecdsa
	IdentityFile ~/.ssh/id_dsa%                                                                                                                                                 username@MBP ~ % ~/.kr/krd-agent.sock
zsh: permission denied: /Users/username/.kr/krd-agent.sock
username@MBP ~ % /usr/local/bin/krssh %h %p
could not connect to remote: dial tcp: lookup tcp/%p: nodename nor servname provided, or not known

Can somebody help me? Thanks

Edit:
username@MBP .kr % ls -lah
total 40
drwx------  13 username  staff   416B 25 mar 21:21 .
drwxr-xr-x+ 24 username  staff   768B 25 mar 21:20 ..
-rw-r--r--@  1 username  staff    73B 25 mar 21:21 bt_peripheral_cache
srwxr-xr-x   1 username  staff     0B 25 mar 21:20 krd-agent.sock
srwxr-xr-x   1 username  staff     0B 25 mar 21:20 krd-hostauth.sock
srwxr-xr-x   1 username  staff     0B 25 mar 21:20 krd.sock
-rw-r--r--   1 username  staff     0B 25 mar 21:20 krd_stderr.log
-rw-r--r--   1 username staff     0B 25 mar 21:20 krd_stdout.log
-rwx------   1 username  staff    10B 25 mar 21:21 last_update_check
-rwx------   1 username  staff    64B 25 mar 21:21 latest_versions_cache
-rwx------   1 username  staff   209B 25 mar 21:21 me
drwx------   5 username  staff   160B 25 mar 21:26 notify
-rwx------   1 username  staff   404B 25 mar 21:21 pairing.json

I do have right permissions for krd-agent.sock

**Comment by FernandoMiguel** [comment]
sometimes i have this happen.
usually testing the connectivity to AWS or moving the phone from wifi to 4G helps

**Comment by agrinman** [comment]
You can use `kr debugaws` to debug connectivity.
Is this still an issue for you? If so please re open and we'll debug.
