### ISSUE TITLE
krypton ssh stops to work after upgrading to macOS Catalina 10.15.5

### ISSUE THREAD

**Issue by joseluisrt** [kryptco/kr#307]
I have just upgraded macOS to Catalina 10.15.5 and ssh using krypton has stopped to work. First I got an error `Enter PIN for 'Kryptonite iOS':` which I solved removing line `PKCS11Provider /usr/local/lib/kr-pkcs11.so` from .ssh/config like explained in https://github.com/kryptco/kr/issues/301

However, after doing that, it seems like trying to get confirmation from iPhone is never tried.

I get this:

```
ssh username@192.168.0.4                
no such identity: /Users/username/.ssh/id_krypton: No such file or directory
no such identity: /Users/username/.ssh/id_ed25519: No such file or directory
no such identity: /Users/username/.ssh/id_ecdsa: No such file or directory
no such identity: /Users/username/.ssh/id_dsa: No such file or directory
jlr@192.168.0.4: Permission denied (publickey).
```

My config file is:

```
# Added by Krypton
Host *
        ProxyCommand /usr/local/bin/krssh %h %p
        IdentityFile ~/.ssh/id_krypton
        IdentityFile ~/.ssh/id_ed25519
        IdentityFile ~/.ssh/id_rsa
        IdentityFile ~/.ssh/id_ecdsa
        IdentityFile ~/.ssh/id_dsa
```

I was able to connect just before the update to Catalina 10.15.5, no changes on the server side.

I have tried to reinstall kr and also unpair and pair again the device, but none of these solved the problem.

Pd. Also asked in https://serverfault.com/questions/1020257/krypton-ssh-stops-to-work-after-upgrading-to-macos-catalina-10-15-5

**Comment by lumaxis** [comment]
I believe you might be missing the `IdentityAgent` setting?
```
	IdentityAgent ~/.kr/krd-agent.sock
```

**Comment by joseluisrt** [comment]
Thank you very much @lumaxis ! I added that line to .ssh/config and everything works again.

**Comment by seadowg** [comment]
I'm seeing the same problem. Everything works properly with git but ssh just fails with:

```
no such identity: /Users/username/.ssh/id_ed25519: No such file or directory
no such identity: /Users/username/.ssh/id_rsa: No such file or directory
no such identity: /Users/username/.ssh/id_ecdsa: No such file or directory
no such identity: /Users/username/.ssh/id_dsa: No such file or directory
username@0.0.0.0: Permission denied (publickey).
```

My `~/.ssh/config` is:

```
# Added by Krypton
Host *
	IdentityAgent ~/.kr/krd-agent.sock
	ProxyCommand /usr/local/bin/krssh %h %p
	IdentityFile ~/.ssh/id_krypton
	IdentityFile ~/.ssh/id_ed25519
	IdentityFile ~/.ssh/id_rsa
	IdentityFile ~/.ssh/id_ecdsa
	IdentityFile ~/.ssh/id_dsa
```

**Comment by 00xkhaled** [comment]
did you find a solution @seadowg

**Comment by seadowg** [comment]
@00xkhaled no! I moved away from Krypton and am using [1Password's SSH tools now](https://developer.1password.com/docs/ssh/).
