### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by cro** [kryptco/kr#310]
Sorry to abuse the issue tracker but I don't know where else to ask this question.  Can someone knowledgeable comment on the status and future of Krypton?  It is a fantastic tool, as an end user I would pay money for it.  Since the Akamai acquisition there doesn't appear to be a lot of activity in the repo.  After the acquisition I switched back from Krypton to my Yubikey for ssh and gpg signing, then yesterday my Yubikey stopped working and I was locked out of my company Amazon account so I took another look at the project.  I was encouraged to see KryptonDesktop for Safari support had arrived.  Any word?

**Comment by tiernano** [comment]
yea. wondering this myself... its a year since any code has been checked into the repo... radio silence from the devs... the site, weirdly for a company owned by a CDN, is very slow at times too... should we start moving to a different SSH provider?

**Comment by rknall** [comment]
Any update on the status of this project?

**Comment by agrinman** [comment]
Krypton WebAuthn/FIDO2 for web-based authentication is very much in active development -- we have a number of exciting updates coming soon.

That said, the `kr` developer cli side of Krypton is not currently in active development. This may change after we our upcoming release...please stay tuned.

--Alex
