### ISSUE TITLE
iOS does not show notifications

### ISSUE THREAD

**Issue by zobo** [kryptco/kr#318]
Is anybody else seeing an issue on iOS 14.2 that notifications don't show when a signature is requested. If I open the app, the (system) notification is shown and also the popup inside the app (asking for confirmation).

**Comment by dmytroleonenko** [comment]
Apple watch notification is delivered though

**Comment by zobo** [comment]
I also have an Apple Watch now. Did not have it before. But I only ever get a popup when the app is open. I think it's not allowed to run in the background.

**Comment by zobo** [comment]
This actually belongs here: https://github.com/kryptco/krypton-ios/issues/129
