### ISSUE TITLE
Request support Apple Silicon

### ISSUE THREAD

**Issue by xuanyunhui** [kryptco/kr#319]
ruining@ruinings-MacBook-Air ~ % curl https://krypt.co/kr | sh    
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8585  100  8585    0     0   6568      0  0:00:01  0:00:01 --:--:--  6568
kr: Installing Krypton...
kr: Unsupported OS X version 11.0. Krypton requires 10.11+
ruining@ruinings-MacBook-Air ~ % uname -a
Darwin ruinings-MacBook-Air.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64

**Comment by rsclarke** [comment]
It seems the installer script was updated to reference Big Sur https://github.com/kryptco/www/commit/845f8bb3801938e299e7764e11760136a8a1d8ed but hasn't been published to the website - @agrinman 

However you can install with (and I've successfully paired on Apple Silicon + Rosetta);

```sh
curl https://raw.githubusercontent.com/kryptco/www/master/kr | sh
```

**Comment by balupton** [comment]
> However you can install with (and I've successfully paired on Apple Silicon + Rosetta);

Not working on a M1 Mac Mini on 11.1
```
balupton@Benjamins-Mac-mini ~ % curl https://raw.githubusercontent.com/kryptco/www/master/kr | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8732  100  8732    0     0  20497      0 --:--:-- --:--:-- --:--:-- 20497
kr: Installing Krypton...
kr: Unsupported OS X version 11.1. Krypton requires 10.11+
```

**Comment by deepfriedheroin** [comment]
same error as above

```
x@Compy ~ % curl https://raw.githubusercontent.com/kryptco/www/master/kr | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8732  100  8732    0     0  29700      0 --:--:-- --:--:-- --:--:-- 29600
kr: Installing Krypton...
kr: Unsupported OS X version 11.1. Krypton requires 10.11+
```

**Comment by balupton** [comment]
@deepfriedheroin you can use my PR in the meantime

```
curl https://raw.githubusercontent.com/kryptco/www/ea93713b45d03a8568b489000e71a0724e82dddd/kr | sh
```

**Comment by joeyfigaro** [comment]
@balupton still same error

**Comment by joeyfigaro** [comment]
For anyone else experiencing this issue, you can find a [working solution here](https://github.com/kryptco/kr/issues/324#issuecomment-872358564)
