### ISSUE TITLE
Haven't been able to pair for 16 hours

### ISSUE THREAD

**Issue by jeblackburn** [kryptco/kr#320]
Hello,

Starting 2020-11-19 at 4:00pm PST, nobody on my team was able to pair with our phones. This is a new problem which we haven't seen before. Until yesterday everything worked fine. Did something change that might have caused the issue?

Thanks.

**Comment by agrinman** [comment]
Not that I know of. Pairing works fine for me. Are you sure you network isnt blocking connections to aws?

**Comment by jeblackburn** [comment]
It was a discrepancy between clocks on client & server. Pilot error. Thanks for checking in.
