### ISSUE TITLE
Reopening Project status (310)

### ISSUE THREAD

**Issue by tiernano** [kryptco/kr#321]
Im re-opening #310 since it was closed in November, but we have not heard anything since... this issue should not be closed till a new release comes out or we have a definate path forward... Since Akamai bought the project, the site hasnt been updated and actually loads very slowly (weirdly for a CDN company), we have had no updates on any of the core applications, and other than "we have stuff in the pipeline" its radio silence... This is an app i would gladly pay money to use, if we had the option, but at this stage, i am starting to look at alternitives... and, the mention that the developer side of things is less of a priority is making me nervous too...

**Comment by vladimyr** [comment]
> Since Akamai bought the project, the site hasn't been updated

The website repo has been updated 3 days ago with a new blog post that sheds some light https://github.com/kryptco/www/blob/c93df00/static/src/blog/_posts/2021-03-18-krypton-is-now-akamai-mfa.md. That being said it hasn't been deployed yet (https://krypt.co/blog/) as of writing this comment.

**Comment by tiernano** [comment]
Looks like they have dropped the announcment on their site at some stage, and its live now... Akamai MFA looks to take over where kr for the browser and smartphone left off, without the dev part... but given they mention "Free Trial" and no where mentions pricing, and given its Akamai, i'm going to guess its not cheap... They do mention the community edition, which will hopefully stay active (fingers crossed) and that is where the dev stuff will live... I am hopeful that the comminity edition will stay active and keep the dev tools part active, but i am also now starting to look at alternitvies...

**Comment by agrinman** [comment]
Hi everyone! We published the announcement here: https://krypt.co/blog/announcements/krypton-is-now-akamai-mfa.html
There are a few FAQs there you can take a look at.
The developer tools will currently remain part of the krypton project only (however we did add 3rd party support of FIDO2/Webauthn in the free Akamai MFA app -- this is free to use for everyone).
We are exploring a developer tools feature set in Akamai MFA (both in the free use product, free for individuals, and service level product features for teams -- will be part of the paid Akamai MFA service). Please stay tuned on the dev topics.
