### ISSUE TITLE
Akamai MFA alternative?

### ISSUE THREAD

**Issue by anned20** [kryptco/kr#323]
Given the [recent announcement](https://krypt.co/blog/announcements/krypton-is-now-akamai-mfa.html) that Krypton will be superseded by Akamai MFA, what is the suitable replacement for the `kr` program?

We use this as a way to secure our SSH and GPG keys on our mobile devices, I can't seem to find an alternative to that.

**Comment by xarbit** [comment]
There is no alternative.. I looked everywhere and haven’t found anything.
We cannot even fork `kr` and continue development because of the licence. 

We would need to start from scratch unless Akamai changes the license for `kr` so we can keep it alive.

**Comment by billstanden** [comment]
I've been digging for this as well and come up empty handed.

I think something halfway simple might be buildable to cover Macs paired with iOS devices and I'm going to take a look at exploring that in some more depth over the next couple of months but that's not going to cover the field.

Anything else, even cobbled together, at this point seems to at best replicate the on device approval but without the offloading.

**Comment by xarbit** [comment]
@billstanden @anned20 

I think we could use this as a kickstart and transform it to what we need? 
https://github.com/sekey/sekey

**Comment by anned20** [comment]
Good find, but it looks like that is specifically made for Macs that use a (separate) secure enclave processor. Those are also in iPhones and iPads, but that would work differently. What the current kr utility does is ask the app on your phone for encryption, not ask the device itself.

**Comment by xarbit** [comment]
that's right, I know .. I am looking in to it .. just to get a feeling of the steps that need to be done. 
I mean creating an App for iOS that stores keys in the phones secure enclave and communicates over a socket (or whatever apple has to offer) to Mac/Linux host + ssh's IdentityAgent & ProxyCommand should be doable.

**Comment by xarbit** [comment]
here is more 

https://github.com/maxgoedjen/secretive

**Comment by feld** [comment]
The SSH key on my iPhone Secure Enclave was the only reason I used Krypton. The loss of this amazing feature is heartbreaking. I would have paid for this feature.

**Comment by bas-d** [comment]
Hi, we've been working for a few years on [Chiff](https://chiff.app). It is based on the same concept, in the sense that it's an app on your phone that serves as an authenticator. Like Krypton, an encrypted communication channel can be set up between browser and phone by scanning a QR-code. After this, authentication requests can be authorized on the phone. Other than Krypton, the main focus has been to support this flow for password authentication, but it also works with WebAuthn.

If there's any interest, we'd consider adding support for signing SSH and/or GPG. What is already present:
1. iOS app in [App Store](https://ios.chiff.app).
2. Android app in [Play store](https://android.chiff.app).
3. Browser extension for [Chrome](https://chrome.google.com/webstore/detail/keyn/gmibdjdkbbogofjhcjaegbpflbfglmhm) / [Firefox](https://chiff.app/assets/downloads/chiff-firefox-2.10.0.xpi) / [Safari](https://apps.apple.com/app/id1361749715) / [Brave](https://chrome.google.com/webstore/detail/keyn/gmibdjdkbbogofjhcjaegbpflbfglmhm) / [Edge](https://microsoftedge.microsoft.com/addons/detail/mgkcdfhpeldhfnldogobgkkopjabbhnj).
4. Formally verified end-to-end encrypted communication protocol.
5. Server component that relays push messages to phone and responses back to computer.

The source code for the app (native iOS and Android apps) and browser extension is currently closed source, but we're planning to make it public in the near feature (although probably not under an open source license).

What would need to be done is to create a command-line interface and integrate with SSH and/or GPG. Assuming there's interest of people here to contribute, the command-line program could be developed under an open-source license.
Perhaps @agrinman would consider relicensing this repo under an open source license (if that doesn't conflict with their plans with Akamai). Although that would greatly speeds things up, I think just rebuilding the CLI would make it considerably less work compared to building all components from scratch :). 

Looking forward to hearing your opinions.

**Comment by agrinman** [comment]
Hi -- Akamai MFA will very likely integrate the SSH functionality over the coming year, but we cannot commit to it just yet.
In the mean time we're working on the right community licensing of kr/krypton so that folks involved in the community can still contribute to it, run it + modifications on their own devices, and contribute changes upstream. Only non-commercial use cases will be supported, which would not allow other apps distributed on the stores to run utilize krypton.
