### ISSUE TITLE
handle no netcat (nc) on RHEL

### ISSUE THREAD

**Issue by kcking** [KryptCo/kr#46]

**Comment by elfchief** [comment]
But, uh, RHEL has netcat?

Though if you rely on it, yeah, you need to list it as a dependency in the rpm, which you're not currently doing.

**Comment by kcking** [comment]
The bare distro I had seemed to be missing it (as nc at least) but we no longer have the netcat fallback in the sshconfig, so I'll close this. Thanks for writing!

**Comment by elfchief** [comment]
Yeah, it's probably not installed by default, but that's why $deity invented dependencies. ;)
