### ISSUE TITLE
Make a more permissive license

### ISSUE THREAD

**Issue by pieterlange** [kryptco/kr#50]
Is this free/libre software or commercially licensed?

**Comment by dolmen** [comment]
If the strange license is used to discourage contribution (at least for now) it would be better to disable the "Pull requests" tab on GitHub.

**Comment by stigtsp** [comment]
I hope you will go for an open source license. :)

**Comment by blimey85** [comment]
Any update on this? Has a license been chosen?

**Comment by agrinman** [comment]
@blimey85 not yet, our primary goal right now is to keep the source public and audit-able, but we're not yet sure how we want the community to contribute. 

We have a big new release coming out (Kryptonite for teams) in the next month so we'll have a better idea then. We definitely do plan to open source some components, so please stay tuned :)

**Comment by pieterlange** [comment]
The best people will not be able to even read the code, let alone be able to make any contribution (audit or pull request) without kryptco making it very explicit that there won't be any copyright claims for other projects these people might be working on.

**Comment by agrinman** [comment]
@pieterlange we can give and have given a few people explicit permission to contribute when they reach out to us to audit the code/add features/fix minor bugs

**Comment by klausenbusk** [comment]
~9 months later. Any update on this?

**Comment by djasa** [comment]
> ~9 months later. Any update on this?

Another year has passed. Are you guys & gals @kryptco any closer to resolving this? Krypton looks really cool but without solving this, I'm afraid you're limiting its potential…

**Comment by agrinman** [comment]
We don't have an update on this yet sorry

**Comment by pieterlange** [comment]
I'd like to be sure i don't need to go through the whole spiel of explaining why OSS licenses are in many ways restricting permissions in order to create a broader appeal/use for a product (such as this).

To be clear: if you publish your sourcecode, you *need* to attach a permissive license to it if you want it to be read, otherwise your honest efforts might be interpreted as a trap.

Please create some clarity around this, you had something cool 2 years ago but right now it seems like you're wasting it.
