### ISSUE TITLE
Breaks ssh operations when using fish-shell

### ISSUE THREAD

**Issue by nathanpalmer** [KryptCo/kr#56]
I just installed this and ran through the pair process. Now whenever I try to ssh or use git (with ssh authentication) I'm simply getting an error.

```
Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
fish: exec `find /usr/local/bin/krssh 2>/dev/null || which nc` github.com 22
                                                   ^

ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kcking** [comment]
I'll have a fix deployed for this tonight. Thanks for reporting!

**Comment by kcking** [comment]
Now fixed for mac -- running "kr upgrade" should fix it for you. Let us know how it goes!

**Comment by nathanpalmer** [comment]
That worked! I just reinstalled `kr` and am no longer getting those errors.
