### ISSUE TITLE
Cryptic error when trying to add GitHub without X

### ISSUE THREAD

**Issue by michaelmior** [kryptco/kr#59]
If I run `kr github` without an X session available, I get the cryptic error `exit status 1`. Without digging into it, I assume it's because the clipboard is unavailable to paste the key. It would be nice if in this case, the key could just be printed to the terminal so I can copy it myself. Or at least the error message should say what actually went wrong.

**Comment by kcking** [comment]
Sure thing, will look into it! For now, running "kr me" will print your key to stdout.

**Comment by kcking** [comment]
This has been fixed, let us know if you have any more issues!
