### ISSUE TITLE
Provide option to make kr work only using Bluetooth

### ISSUE THREAD

**Issue by jauderho** [KryptCo/kr#61]
This would be intended to require that the phone be physically close vs other transports.

**Comment by kcking** [comment]
Agreed, but we would enforce this at the phone. I'll make an issue in our android/ios repos. Thanks for the post!

**Comment by noamtamim** [comment]
How do I enable signing via bluetooth? I don't see such option.

**Comment by agrinman** [comment]
@noamtamim Bluetooth is only supported on the macOS `kr` cli currently (linux and browser extensions for U2F do not currently have bluetooth support). Ensure bluetooth is turned on on both your phone and computer. It should work automatically by doing a silent BLE pairing.

**Comment by noamtamim** [comment]
@agrinman so it should work when I sign git commits on my Mac? 
What exactly do I have to do to make it work? Right now, bluetooth is enabled on both the Mac and the phone (Pixel 1), but if I turn off mobile data and wifi on the phone, nothing happens.

**Comment by agrinman** [comment]
@noamtamim yes it should, you can also try `ssh me.krypt.co` to test it. Try toggling bluetooth on both macos and android and terminating and re-opening the app. If it's still not working send us an email at `support at krypt.co` to further debug.
