### ISSUE TITLE
Installation fails to start krd when run under tmux (and screen?)

### ISSUE THREAD

**Issue by smw** [kryptco/kr#65]
```
2.3.0 sim:~  $ curl https://krypt.co/kr | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8785  100  8785    0     0  27098      0 --:--:-- --:--:-- --:--:-- 27114
kr: Installing Kryptonite...
kr: Downloading Kryptonite.
######################################################################## 100.0%
kr: OpenSSL command line found, verifying downloaded binary hash...
kr: Binary verified.
/Users/smw/Library/LaunchAgents/co.krypt.krd.plist: Operation not permitted
kr: Kryptonite installed successfully. Type "kr pair" to pair with the Kryptonite mobile app.
2.3.0 sim:~ $ kr pair
Could not connect to Kryptonite daemon. Make sure it is running by typing "kr restart".
```

This appears to be a known 'bug' running launchctl under tmux and screen, see https://superuser.com/a/898585.

Running `launchctl load /Users/smw/Library/LaunchAgents/co.krypt.krd.plist` in a seperate terminal window (no tmux) appears to fix the issue.

I don't know if there's an easy fix, other than documenting that the install shouldn't be done under a terminal multiplexer, but it's possible that somehow `reattach-to-user-namespace` might be related to the issue?

**Comment by smw** [comment]
https://github.com/tmux/tmux/issues/600 tends to confirm the `reattach-to-user-namespace` suggestion.

**Comment by kcking** [comment]
We now use `reattach-to-user-namespace` for all commands run by `kr` :)
