### ISSUE TITLE
approval notification adds space around "@" in email address

### ISSUE THREAD

**Issue by jorangreef** [KryptCo/kr#67]
The approval notification on iOS shows the email address with spaces around the "@".

It should show the email address as the user entered it, and as it exists as a comment in the public key.

**Comment by kcking** [comment]
Are you referring to the "username" @ "host" in the notification? We space them out to make it more readable. We don't show the comment of the key in the notification, just the name of the paired device and the username and host of the login

**Comment by jorangreef** [comment]
Yes, I assumed it was referencing the comment in the private key being used (my email address and username@host happen to match).

But it makes sense that it should provide the purpose for which the private key is being used as it does currently (i.e. the username@host target destination) since only one private key can be used at present. As an aside, when more than private key is supported, the notification should indicate both the key being used, and the target destination.

Still, after using the app, I would prefer the identifier to just match up with what is typed: "ssh joran@ronomon.com". The spaces feel overwrought.
