### ISSUE TITLE
Bash On Ubuntu on Windows 14.04, Starting the daemon fails silently

### ISSUE THREAD

**Issue by d3xter** [kryptco/kr#71]
I'm running Bash on Ubuntu on Windows 14.04

    # lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04.4 LTS
    Release:        14.04
    Codename:       trusty

    # uname -a
    Linux HOST 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux

Restarting the server doesn't show any errors:

    # kr restart
    Restarted Kryptonite daemon.

But it seems like the daemon isn't started at all:

    # kr me
    Could not connect to Kryptonite daemon. Make sure it is running by typing "kr restart".

    # ps ax | grep kr
    446 ?        S      0:00 grep --color=auto kr

**Comment by kcking** [comment]
Thanks for writing. I believe this is a systemd issue. We are looking into an alternate daemon architecture for linux that should solve this

**Comment by kcking** [comment]
Working on this now -- follow the first issue here: #54

**Comment by kcking** [comment]
Should now be fixed, let me know if you have any more issues after a "kr upgrade"

**Comment by codexss** [comment]
still can't start service
![image](https://cloud.githubusercontent.com/assets/5959201/25699197/cdf573f6-30f4-11e7-9ada-738cfd448e44.png)

**Comment by d3xter** [comment]
Still not working. installed 2.0.5a with "kr upgrade".

Now I get the following:

    Kryptonite is now installed! Type "kr pair" to pair with the Kryptonite phone app.
    # kr -v
    kr version 2.0.5
    # kr me
    Kryptonite ▶ Restarting krd...
    Kryptonite ▶ Restarting krd...
    Could not connect to Kryptonite daemon. Make sure it is running by typing "kr restart".
    # kr restart
    Restarted Kryptonite daemon.
    # kr me
    Kryptonite ▶ Restarting krd...
    Kryptonite ▶ Restarting krd...
    Could not connect to Kryptonite daemon. Make sure it is running by typing "kr restart".
    # kr pair
    Kryptonite ▶ Restarting krd...
    Kryptonite ▶ Restarting krd...
    Could not connect to Kryptonite daemon. Make sure it is running by typing "kr restart".

**Comment by kcking** [comment]
What version of windows are you running? We have been discussing on https://github.com/kryptco/kr/issues/54 and it seems like only the developer/insider build of windows works. Once that build gets rolled out to stable, it should be fixed for you.

**Comment by d3xter** [comment]
I'm running Windows 10 Pro with Build 14393.1066.

Ok, thank you.
Will wait for updates then.
