### ISSUE TITLE
Unable to ssh

### ISSUE THREAD

**Issue by Idnan** [KryptCo/kr#82]
After installing the `kr` on mac through `curl` i am getting following error while doing ssh.

dlopen /usr/lib/kr-pkcs11.so failed: dlopen(/usr/lib/kr-pkcs11.so, 2): image not found
zsh:1: no such file or directory: /usr/bin/krssh
ssh_exchange_identification: Connection closed by remote host

**Comment by kcking** [comment]
What operating system are you running?

**Comment by Idnan** [comment]
macOS Sierra v10.12.4

**Comment by kcking** [comment]
Do `/usr/local/lib/kr-pkcs11.so` and `/usr/local/bin/krssh` exist? Changing your `~/.ssh/config` to those filepaths should fix the issue.

Also what method did you use to install kr?

**Comment by Idnan** [comment]
Thanks its fixed now. I used `curl` method.
```
curl https://krypt.co/kr | sh
```
