### ISSUE TITLE
Group or remove gcloud/aws/etc. commands

### ISSUE THREAD

**Issue by joushou** [kryptco/kr#85]
About half of the kr commands are simple `kr copy && xdg-open ${CONFIGURATION_URL}` aliases. This makes the help text rather noisy.

I can think of two potential solutions to the problem:

1. Make an "addsite" command that takes the site as argument.
2. Remove the aliases entirely.

I'm tempted by the second solution. Adding a public key to these pages are by no means a Kryptonite specific task, and kr is already providing plenty of convenience with "kr copy".

Not only that, maintaining an up to date directory of popular sites accepting asymmetric SSH authentication and their potentially often changing configuration URL's seem like a silly task to take on. It also seems like a classic case of feature creep to me.

I'm not sure if other users or maintainers will agree with me on that. I'd be okay with solution 1.

**Comment by kcking** [comment]
Thank you for the thoughts on this.
I agree the help text is noisy. In the short term, I think it's best to list all of the sites on a single line of help text. Some users don't know where to upload their public key if they are using SSH public keys for the first time, but using "kr addsite" would imply they already know where to upload their key.

**Comment by joushou** [comment]
If the goal is to help asymmetric first-timers (which I guess is fair), wouldn't a simple link in the help-text to a guide at krypt.co that could describe, potentially even with screenshots if necessary, how to do it? It would also be easier to keep up to date.
