### ISSUE TITLE
/root/.ssh/config: line 1: Bad configuration option: \\n#

### ISSUE THREAD

**Issue by CHERTS** [kryptco/kr#88]
Hi,

`# lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

`# kr -v`
kr version 2.0.5

`# ssh root@myhost`
/root/.ssh/config: line 1: Bad configuration option: \\n#
/root/.ssh/config: terminating, 1 bad configuration options

`# cat /root/.ssh/config`
\n# Added by Kryptonite\nHost *\n\tPKCS11Provider /usr/lib/kr-pkcs11.so\n\tProxyCommand /usr/bin/krssh %h %p\n\tIdentityFile ~/.ssh/id_kryptonite\n\tIdentityFile ~/.ssh/id_ed25519\n\tIdentityFile ~/.ssh/id_rsa\n\tIdentityFile ~/.ssh/id_ecdsa\n\tIdentityFile ~/.ssh/id_dsa

**Comment by kcking** [comment]
Thanks for posting, what shell are you using?
