### ISSUE TITLE
Kryptonite not working as sudo

### ISSUE THREAD

**Issue by CHERTS** [kryptco/kr#90]
Hi,

Kryptonite not working in Debian 8.7

`# lsb_release -a`
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie

`# whoami`
root

`# kr -v`
kr version 2.0.5

`# cat ~/.ssh/config`
`# Added by Kryptonite`
Host *
        PKCS11Provider /usr/lib/kr-pkcs11.so
        ProxyCommand /usr/bin/krssh %h %p
        IdentityFile ~/.ssh/id_kryptonite
        IdentityFile ~/.ssh/id_ed25519
        IdentityFile ~/.ssh/id_rsa
        IdentityFile ~/.ssh/id_ecdsa
        IdentityFile ~/.ssh/id_dsa

`# ls -la ~/.ssh/`
total 72
drwx------  2 root root  4096 May  4 21:12 .
drwx------ 30 root root  4096 May  4 21:12 ..
-rw-r--r--  1 root root  1039 May  4 15:38 authorized_keys
-rw-r--r--  1 root root   581 May  4 21:12 config
-rw-r--r--  1 root root   325 May  4 20:45 config.bak1
-rwx------  1 root root   750 May  4 20:50 id_kryptonite.pub
-rw-------  1 root root  1679 Jun  3  2015 id_rsa
-rw-r--r--  1 root root   393 Jun  3  2015 id_rsa.pub
-rw-------  1 root root 18250 May  4 15:51 known_hosts

`# kr pair`
...

`# kr me`
ssh-rsa AAAAB3.....== sleuthhound@xxxx.ru

I add public ssh-rsa key to myremotehost.ru in file .ssh/authorized_keys

`# ssh myuser@myremotehost.ru -vvvv`
````
OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 19: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Executing proxy command: exec /usr/bin/krssh myremotehost.ru 22
debug1: permanently_set_uid: 0/0
debug1: permanently_drop_suid: 0
debug1: identity file /root/.ssh/id_kryptonite type 1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_kryptonite-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: identity file /root/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u3
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.7p1 Debian-5+deb8u3
debug1: match: OpenSSH_6.7p1 Debian-5+deb8u3 pat OpenSSH* compat 0x04000000
debug2: fd 5 setting O_NONBLOCK
debug2: fd 4 setting O_NONBLOCK
debug3: load_hostkeys: loading entries for host "myremotehost.ru" from file "/root/.ssh/known_hosts"
debug3: load_hostkeys: found key type ECDSA in file /root/.ssh/known_hosts:20
debug3: load_hostkeys: loaded 1 keys
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-ed25519,ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: mac_setup: setup umac-64-etm@openssh.com
debug1: kex: server->client aes128-ctr umac-64-etm@openssh.com none
debug2: mac_setup: setup umac-64-etm@openssh.com
debug1: kex: client->server aes128-ctr umac-64-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX
debug3: load_hostkeys: loading entries for host "myremotehost.ru" from file "/root/.ssh/known_hosts"
debug3: load_hostkeys: found key type ECDSA in file /root/.ssh/known_hosts:20
debug3: load_hostkeys: loaded 1 keys
debug1: Host 'myremotehost.ru' is known and matches the ECDSA host key.
debug1: Found key in /root/.ssh/known_hosts:20
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /root/.ssh/id_kryptonite (0x7f71dfb5eaa0), explicit
debug2: key: /root/.ssh/id_ed25519 ((nil)), explicit
debug2: key: /root/.ssh/id_rsa (0x7f71dfb5eb40), explicit
debug2: key: /root/.ssh/id_ecdsa ((nil)), explicit
debug2: key: /root/.ssh/id_dsa ((nil)), explicit
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /root/.ssh/id_kryptonite
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: pkalg ssh-rsa blen 535
debug2: input_userauth_pk_ok: fp YY:YY:YY:YY:YY:YY:YY:YY:YY:X:XX:XX:1d:73:58:YY
debug3: sign_and_send_pubkey: RSA ZZ:ZZ:ZZ:ZZ:ZZ:ZZ:ZZ:ZZ:ZZ:ZZ:ZZ:ZZ:1d:73:58:ZZ
no such identity: /root/.ssh/id_kryptonite: No such file or directory
debug1: Trying private key: /root/.ssh/id_ed25519
no such identity: /root/.ssh/id_ed25519: No such file or directory
debug1: Offering RSA public key: /root/.ssh/id_rsa
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /root/.ssh/id_ecdsa
no such identity: /root/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_dsa
no such identity: /root/.ssh/id_dsa: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
myuser@myremotehost.ru's password:
````

After run ssh, the password of the user myuser was requested, authorization of the rsa keys via Kryptonite did not work, what should I do?

**Comment by kcking** [comment]
does `ssh me.krypt.co` work?

It looks like you have not added your kryptonite public key to your server. `kr add <user@server`, then typing your password will add the kryptonite public key to `~/.ssh/authorized_keys` on that server and use kryptonite on future logins.

**Comment by kcking** [comment]
Sorry I just read that you added the key to the server already -- looks like SSH isn't hitting our agent.

Can you try `SSH_AUTH_SOCK=$HOME/.kr/krd-agent.sock ssh <user@server>`?

**Comment by kcking** [comment]
I also have a feeling that updating your openSSH client may resolve this

**Comment by CHERTS** [comment]
``# ssh me.krypt.co``

The authenticity of host 'me.krypt.co (<no hostip for proxy command>)' can't be established.
RSA key fingerprint is bc:0f:28:fd:ed:33:16:97:15:9d:27:70:ed:f9:9e:b8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'me.krypt.co' (RSA) to the list of known hosts.
no such identity: /root/.ssh/id_kryptonite: No such file or directory
no such identity: /root/.ssh/id_ed25519: No such file or directory

It looks like you are not using a Kryptonite SSH key. Make sure kr is installed on this workstation and paired with Kryptonite.
Check out https://krypt.co/faq/ for more information.

Connection to me.krypt.co closed.


Using command
``# SSH_AUTH_SOCK=$HOME/.kr/krd-agent.sock ssh myuser@myremotehost.ru -vvvv``
does not work, the user's password is requested.

>>I also have a feeling that updating your openSSH client may resolve this

I have the latest version of Debian Stable installed
On which Linux distribution and with which version of OpenSSH does it work for you?

**Comment by kcking** [comment]
```
Linux Mint 18 Sarah, OpenSSH_7.2p2
RHEL 7.3, OpenSSH_6.6.1
CentOS 7, OpenSSH_6.6.1
```
I have those three working, and they have earlier versions of OpenSSH so I don't think that's the problem.

Can you show `ls -la ~/.kr/krd-agent.sock` please?

**Comment by CHERTS** [comment]
I noticed that when you start krd, the socket is created in the /home/cherts/.kr/krd-agent.sock directory.
I execute "kr restart" from under the user root.

`# ls -la ~/.kr/`
total 12
drwx------  3 root root 4096 May  4 22:10 .
drwx------ 30 root root 4096 May  4 21:12 ..
drwx------  2 root root 4096 May  4 20:33 notify
lrwxrwxrwx  1 root root   31 May  4 22:10 original-agent.sock -> /home/cherts/.kr/krd-agent.sock

`# ls -ls /home/cherts/.kr/`
total 52
 1 srwxr-xr-x 1 root root   0 May  4 20:45 krd-agent.sock
 1 srwxr-xr-x 1 root root   0 May  4 20:45 krd-hostauth.sock
 1 srwxr-xr-x 1 root root   0 May  4 20:45 krd.sock
 5 -rwx------ 1 root root  10 May  4 20:49 last_update_check
 5 -rwx------ 1 root root  46 May  4 20:49 latest_versions_cache
 5 -rwx------ 1 root root 774 May  4 20:47 me
33 drwx------ 2 root root  29 May  4 22:10 notify
 5 -rwx------ 1 root root 411 May  4 20:47 pairing.json

`# ps -auxw |grep krd`
root     14656  0.0  0.0 349864 10280 ?        Sl   20:45   0:00 /usr/bin/krd &

**Comment by kcking** [comment]
Ah yes since we don't require root we drop down to $SUDO_USER
Can you try `export SUDO_USER=""; kr restart; ssh me.krypt.co`?

**Comment by CHERTS** [comment]
Yah! It's working.

`# export SUDO_USER=""`
`# kr restart`
`# rm -rf /home/cherts/.kr`
`# kr pair`
`# kr add cherts@myremoteserver`
`# ssh cherts@myremoteserver`

`Kryptonite ▶ Requesting SSH authentication from phone`
`Kryptonite ▶ Phone approval required. Respond using the Kryptonite app`
`Kryptonite ▶ Success. Request Allowed ✔`

**Comment by CHERTS** [comment]
You need to add
export SUDO_USER=""
in the installation file https://krypt.co/kr

**Comment by kcking** [comment]
Great to hear that it works. I am going to add fix within krd that should resolve this without any environment changes.

**Comment by CHERTS** [comment]
> I am going to add a fix within krd that should resolve this without any environment changes.

Well, I will wait for these fix.

Thank you for best project!
