### ISSUE TITLE
Not able to pair devices

### ISSUE THREAD

**Issue by sushi86** [kryptco/kr#95]
First of all, thanks for the quick fix for installing on debian =)

But know I'm not able to get it running, see here, **after pairing**, I get this:

```
root@CENSORED:~/.ssh# ssh me.krypt.co
Kryptonite ▶ Workstation not yet paired. Please run "kr pair" and scan the QRCode with the Kryptonite mobile app.
no such identity: /root/.ssh/id_kryptonite: No such file or directory
no such identity: /root/.ssh/id_ed25519: No such file or directory
no such identity: /root/.ssh/id_rsa: No such file or directory
no such identity: /root/.ssh/id_ecdsa: No such file or directory
no such identity: /root/.ssh/id_dsa: No such file or directory
Permission denied (publickey).

root@CENSORED:~/.ssh# kr me
Request timed out. Make sure your phone and workstation are paired and connected to the internet and the Kryptonite app is running.

root@CENSORED:~/.ssh# kr add CENSORED.CENSORED@outlook.de
error retrieving your public key: %!(EXTRA string=Request timed out. Make sure your phone and workstation are paired and connected to the internet and the Kryptonite app is running.)

```

I have no proxy installed. This is a root server with free internet access. Also my mobile phone has internet access.

Anything else I can check?

**Comment by kcking** [comment]
What is the output of `echo $SUDO_USER`? We drop priviliges back to the original user to run `krd` since it doesn't need root, but a bug was just fixed with this (not released yet).

A workaround is to `export SUDO_USER=""; kr restart` so that everything is run as root.

**Comment by sushi86** [comment]
```
echo $SUDO_USER

root@CENSORED:~# 
```

Response is empty, also workaround doesn't work unfortunatly :(

**Comment by kcking** [comment]
Just to confirm -- `kr pair` succeeds and outputs an SSH public key, but `kr me` times out?

**Comment by sushi86** [comment]
kr me still times out

The app gave me successful paired message. But no keys are created:
```
no such identity: /root/.ssh/id_kryptonite: No such file or directory
no such identity: /root/.ssh/id_ed25519: No such file or directory
no such identity: /root/.ssh/id_rsa: No such file or directory
no such identity: /root/.ssh/id_ecdsa: No such file or directory
no such identity: /root/.ssh/id_dsa: No such file or directory
```

**Comment by kcking** [comment]
A success message should be printed by `kr pair` as well, it sounds like the response from the phone is not making it back to your computer. Do you see anything suspicious in `~/.kr/krd.log`?

**Comment by sushi86** [comment]
I have not such a log file.

But you're right. On my PC I don't get a success message.

**Comment by kcking** [comment]
The logs might also go to wherever system logs are kept on your machine (I've seen `/var/log/syslog` and `/var/log/messages`)

**Comment by sushi86** [comment]
Ok I taillogged both logs:

/var/log/messages:
```
May  5 21:04:07 skrauss krd[12435]: 21:04:07.927 NOTICE ▶ pushing alert for request 5tRjCHLMhhqYGfQ8SFschr
May  5 21:04:09 skrauss krd[12435]: 21:04:09.040 NOTICE ▶ SendQueued: Pairing in progress, waiting for symmetric key
May  5 21:04:09 skrauss krd[12435]: 21:04:09.341 WARNIN ▶ SQS queue DFDB6668-AA48-BD40-4E30-3A02767AA145-responder does not exist, creating
May  5 21:04:13 skrauss krd[12435]: 21:04:13.040 NOTICE ▶ pushing alert for request 1F6AQkqANTnJVtzsTHSWNp
May  5 21:04:29 skrauss krd[12435]: 21:04:29.323 NOTICE ▶ SendQueued: Pairing in progress, waiting for symmetric key
May  5 21:04:29 skrauss krd[12435]: 21:04:29.538 WARNIN ▶ SQS queue B16FDC08-767A-0A24-58B5-EF0AD8820323-responder does not exist, creating
May  5 21:04:33 skrauss krd[12435]: 21:04:33.323 NOTICE ▶ pushing alert for request 1frzL6yivGCbHrkTgo0OyI
---- here I paired via my phone
May  5 21:05:26 skrauss krd[12435]: 21:05:26.380 NOTICE ▶ stored symmetric key
```

/var/log/syslog:
```
May  5 21:04:29 skrauss krd[12435]: 21:04:29.218 ERROR ▶ me request error: Phone not paired
May  5 21:04:29 skrauss krd[12435]: 21:04:29.323 NOTICE ▶ SendQueued: Pairing in progress, waiting for symmetric key
May  5 21:04:29 skrauss krd[12435]: 21:04:29.538 WARNIN ▶ SQS queue B16FDC08-767A-0A24-58B5-EF0AD8820323-responder does not exist, creating
May  5 21:04:33 skrauss krd[12435]: 21:04:33.323 NOTICE ▶ pushing alert for request 1frzL6yivGCbHrkTgo0OyI
---- here I paired via my phone
May  5 21:05:26 skrauss krd[12435]: 21:05:26.380 NOTICE ▶ stored symmetric key
May  5 21:05:39 skrauss krd[12435]: 21:05:39.040 ERROR ▶ Request timed out
May  5 21:05:39 skrauss krd[12435]: 21:05:39.040 ERROR ▶ Request timed out
May  5 21:05:42 skrauss krd[12435]: 21:05:42.076 ERROR ▶ evicting request 1F6AQkqANTnJVtzsTHSWNp
May  5 21:05:59 skrauss krd[12435]: 21:05:59.323 ERROR ▶ Request timed out
May  5 21:05:59 skrauss krd[12435]: 21:05:59.323 ERROR ▶ Request timed out
May  5 21:06:00 skrauss krd[12435]: 21:06:00.462 ERROR ▶ evicting request 1frzL6yivGCbHrkTgo0OyI
```

**Comment by kcking** [comment]
Seems to be an SQS message issue. The response from the phone is a larger message, perhaps it's getting dropped somewhere in the network. Out of curiousity, where are you connecting from?

We might look into fragmenting messages into smaller parts / using multiple AWS regions.

**Comment by sushi86** [comment]
This is a root Server from OVH, I think in Paris.
And I'm from Munich.

Tell me if I can help you with that (more debugging etc)

**Comment by kcking** [comment]
Much appreciated! I'll reach out once we make progress on this

**Comment by kcking** [comment]
Two more questions -- have you paired with any other computers (and how many), and what type of phone are you using?

**Comment by kcking** [comment]
This is likely a clock skew issue (fixed in a recent release) -- please try upgrading kr and Kryptonite and reopen if it hasn't been fixed!

**Comment by serverhiccups** [comment]
I know this issue is really old by now, but I'm getting the same error as sushi86 (in system.log). I'm running macOS Mojave 10.14.3, kr version 2.4.13 and iOS 10 on an iPhone 5c with app version 2.5.5.

I scan the QR code on my phone and it all seems OK (adds an entry for my computer), but the QR code stays up on my computer and eventually times out. Both my devices are in the same time zone, and are physically within Bluetooth range, and on the same WI-Fi network.

I've had this same issue when trying to pair to other computers before, but I recently reinstalled macOS so it's a bit more of a pressing issue.
(This is a really fantastic project, BTW. It's surprising I've gone this long without issues)
