### ISSUE TITLE
`kr restart` doesn't start anything

### ISSUE THREAD

**Issue by grawity** [kryptco/kr#97]
Running `make install` happily installed everything to my `~/.local/bin/` (maybe as a side effect of having $PREFIX set?), but of course that's not where `kr restart` looks – it expects the daemon to be in `/usr/bin`, and _completely silently_ fails to start it. So that's two issues:

 * kr should use $PATH for that (the commit didn't say *why* absolute paths are being used);
 * kr should use a more reliable approach to starting the daemon (slightly disappointed that systemd --user support was dropped) and report errors if they occur.

(...also, does `&` even _work_ in exec.Command? It probably just becomes a krd parameter instead of doing anything shell-like.)

**Comment by kcking** [comment]
Indeed `$PATH` should be used

systemd --user support was dropped because it lacks support in a bunch of distros (CentOS, Ubuntu 14.04 are the two I remember atm)

That being said you should be able to add your own kr.service file to /etc/systemd/user/default.target.wants

**Comment by kcking** [comment]
Thanks for the comments! Let us know if this fixes your setup
